# Generated by Django 3.0.7 on 2020-08-20 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0003_messageoftheday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredbill',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='featuredcommonsdivision',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='featuredlordsdivision',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='featuredperson',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messageoftheday',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
