# Generated by Django 3.0.7 on 2021-04-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0005_zeitgeistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredbill',
            old_name='bill',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='featuredcommonsdivision',
            old_name='division',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='featuredlordsdivision',
            old_name='division',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='featuredperson',
            old_name='person',
            new_name='target',
        ),
    ]
