# Generated by Django 3.2 on 2021-09-02 17:33

from django.db import migrations, models
import util.time


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0006_auto_20210426_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeitgeistitem',
            name='priority',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='featuredbill',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='featuredcommonsdivision',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='featuredlordsdivision',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='featuredperson',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='messageoftheday',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='zeitgeistitem',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
    ]
