# Generated by Django 3.2.4 on 2022-02-17 18:48

import django.db.models.deletion
from django.db import migrations, models

import util.models.generics
import util.time


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0047_auto_20220217_1848"),
        ("surface", "0008_delete_featuredbill"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedBill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="repository.bill",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, util.models.generics.BaseModelMixin),
        ),
    ]
