# Generated by Django 5.1.3 on 2024-11-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surface", "0009_featuredbill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="featuredbill",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="featuredbill",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="featuredcommonsdivision",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="featuredcommonsdivision",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="featuredlordsdivision",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="featuredlordsdivision",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="featuredperson",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="featuredperson",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="messageoftheday",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="messageoftheday",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="zeitgeistitem",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="zeitgeistitem",
            old_name="modified_on",
            new_name="modified_at",
        ),
    ]
