# Generated by Django 5.2.3 on 2025-07-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surface", "0010_rename_created_on_featuredbill_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zeitgeistitem",
            name="reason",
            field=models.CharField(
                choices=[
                    ("feature", "Feature"),
                    ("social", "Social"),
                    ("default", "Default"),
                ],
                default="default",
                max_length=24,
            ),
        ),
    ]
