# Generated by Django 2.2.6 on 2019-11-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='long_name',
            field=models.CharField(blank=True, default='', help_text='Official name', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=16, null=True, unique=True),
        ),
    ]
