# Generated by Django 2.2.6 on 2019-11-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20191110_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='long_name',
            field=models.CharField(blank=True, default=None, help_text='Official name', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='short_name',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True),
        ),
    ]
