# Generated by Django 3.0.2 on 2020-01-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20200109_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblink',
            name='links',
        ),
        migrations.AlterField(
            model_name='person',
            name='full_title',
            field=models.CharField(blank=True, help_text='Official name with honorifics.', max_length=72, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='constituencyresult',
            unique_together={('election', 'constituency'), ('election', 'mp')},
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.DeleteModel(
            name='WebLink',
        ),
    ]
