# Generated by Django 3.0.2 on 2020-01-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20200112_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='governmentpost',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='oppositionpost',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parliamentarypost',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
