# Generated by Django 3.0.2 on 2020-01-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20200112_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='declaredinterest',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='declaredinterestcategory',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organisation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='experiencecategory',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='governmentpost',
            name='hansard_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='governmentpost',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='maidenspeech',
            name='subject',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='oppositionpost',
            name='hansard_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='oppositionpost',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='parliamentarypost',
            name='hansard_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parliamentarypost',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='long_name',
            field=models.CharField(blank=True, default=None, help_text='Official name', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='wikipedia',
            field=models.CharField(blank=True, help_text="Path section of a wikipedia url (e.g. 'John_Baron_(politician)')", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='additional_name',
            field=models.CharField(blank=True, help_text='Middle name(s)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(blank=True, help_text='Last name', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_title',
            field=models.CharField(blank=True, help_text='Official name with honorifics.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.CharField(blank=True, help_text='First name', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Canonical name for this person.', max_length=128),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='address',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='description',
            field=models.CharField(help_text='What kind of address is this? e.g Parliamentary, Constituency...', max_length=128),
        ),
        migrations.AlterField(
            model_name='subjectofinterest',
            name='subject',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='subjectofinterestcategory',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='webaddress',
            name='description',
            field=models.CharField(help_text='What kind of address is this? e.g Twitter, personal site...', max_length=128),
        ),
    ]
