# Generated by Django 3.0.2 on 2020-01-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20200113_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentpost',
            name='hansard_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='governmentpost',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='oppositionpost',
            name='hansard_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='oppositionpost',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='parliamentarypost',
            name='hansard_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='parliamentarypost',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
