# Generated by Django 3.0.2 on 2020-01-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20200113_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='governmentpost',
            name='hansard_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='oppositionpost',
            name='hansard_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='parliamentarypost',
            name='hansard_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='UnlinkedConstituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('constituency', models.ForeignKey(blank=True, help_text='Constituency which this is supposed to refer to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Election')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
