# Generated by Django 3.0.2 on 2020-01-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20200114_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='organisation',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
