# Generated by Django 3.0.2 on 2020-01-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20200114_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='id',
        ),
        migrations.RemoveField(
            model_name='declaredinterest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='declaredinterestcategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='election',
            name='id',
        ),
        migrations.RemoveField(
            model_name='electionnationalresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='governmentpost',
            name='id',
        ),
        migrations.RemoveField(
            model_name='oppositionpost',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parliamentarypost',
            name='id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='committee',
            name='parliamentdotuk',
            field=models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='parliamentdotuk',
            field=models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='declaredinterest',
            name='parliamentdotuk',
            field=models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='declaredinterestcategory',
            name='parliamentdotuk',
            field=models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='parliamentdotuk',
            field=models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='electionnationalresult',
            name='parliamentdotuk',
            field=models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='governmentpost',
            name='parliamentdotuk',
            field=models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='oppositionpost',
            name='parliamentdotuk',
            field=models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='parliamentarypost',
            name='parliamentdotuk',
            field=models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='parliamentdotuk',
            field=models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True),
        ),
    ]
