# Generated by Django 3.0.2 on 2020-03-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20200303_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
