# Generated by Django 3.0.2 on 2020-03-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20200318_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPortrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('year_taken', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fullsize_url', models.URLField(blank=True, null=True)),
                ('square_url', models.URLField(blank=True, null=True)),
                ('wide_url', models.URLField(blank=True, null=True)),
                ('tall_url', models.URLField(blank=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
