# Generated by Django 3.0.2 on 2020-04-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_person_current_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constituencyboundary',
            old_name='boundary',
            new_name='boundary_kml',
        ),
        migrations.AddField(
            model_name='constituencyboundary',
            name='area',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constituencyboundary',
            name='boundary_length',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constituencyboundary',
            name='center_latitude',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constituencyboundary',
            name='center_longitude',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constituencyboundary',
            name='constituency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.Constituency'),
        ),
    ]
