# Generated by Django 3.0.2 on 2020-04-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_auto_20200423_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstituencyAlsoKnownAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('alias', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repository.Constituency')),
                ('canonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repository.Constituency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
