# Generated by Django 3.0.2 on 2020-05-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_constituencyalsoknownas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constituencyalsoknownas',
            options={'verbose_name_plural': 'Constituency AKAs'},
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('parliamentdotuk', models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True)),
                ('electorate', models.PositiveIntegerField(default=0)),
                ('majority', models.PositiveIntegerField(default=0)),
                ('turnout', models.PositiveIntegerField(default=0)),
                ('turnout_fraction', models.DecimalField(decimal_places=3, max_digits=3)),
                ('result', models.CharField(max_length=32)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Election')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConstituencyCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('votes', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('party', models.CharField(max_length=16)),
                ('election_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.ElectionResult')),
            ],
            options={
                'unique_together': {('election_result', 'name')},
            },
        ),
    ]
