# Generated by Django 3.0.2 on 2020-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0021_auto_20200511_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
