# Generated by Django 3.0.2 on 2020-05-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0023_auto_20200511_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituencycandidate',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
