# Generated by Django 3.0.2 on 2020-05-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0024_auto_20200511_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituencycandidate',
            name='party',
            field=models.CharField(max_length=128),
        ),
    ]
