# Generated by Django 3.0.7 on 2021-04-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0026_auto_20200820_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberportrait',
            options={'verbose_name': 'Member Portrait', 'verbose_name_plural': 'Member Portraits'},
        ),
    ]
