# Generated by Django 3.2 on 2021-04-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0028_auto_20210428_1326'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unlinkedconstituency',
            name='unique_election_result',
        ),
        migrations.RenameField(
            model_name='unlinkedconstituency',
            old_name='mp',
            new_name='person',
        ),
        migrations.AddField(
            model_name='unlinkedconstituency',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unlinkedconstituency',
            name='person_won',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unlinkedconstituency',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalsoknownas',
            name='alias',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='constituencyresult',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='constituencyresult',
            constraint=models.UniqueConstraint(fields=('election', 'constituency', 'mp'), name='unique_constituency_result'),
        ),
        migrations.AddConstraint(
            model_name='unlinkedconstituency',
            constraint=models.UniqueConstraint(fields=('name', 'person', 'election'), name='unique_election_result'),
        ),
    ]
