# Generated by Django 3.2 on 2021-04-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0029_auto_20210429_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaredinterest',
            name='description',
            field=models.TextField(),
        ),
    ]
