# Generated by Django 3.2 on 2021-05-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0030_alter_declaredinterest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituencyalsoknownas',
            name='alias',
        ),
        migrations.AddField(
            model_name='constituencyalsoknownas',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constituencyalsoknownas',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='constituencyalsoknownas',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
