# Generated by Django 3.2.4 on 2021-11-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0035_auto_20211029_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['name'], 'verbose_name_plural': 'Parties'},
        ),
        migrations.AlterField(
            model_name='constituencyresult',
            name='mp',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.person'),
        ),
    ]
