# Generated by Django 3.2.4 on 2021-11-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0036_auto_20211101_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partyalsoknownas',
            options={'ordering': ['canonical__name', 'alias'], 'verbose_name': 'PartyAlsoKnownAs', 'verbose_name_plural': 'Parties also known as'},
        ),
    ]
