# Generated by Django 3.2.4 on 2021-11-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0041_alter_lordsdivision_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lordsdivision",
            name="ayes",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="date",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="description",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="division_number",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="modified_on",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="noes",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="session",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="title",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="uin",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="whipped_vote",
        ),
        migrations.RemoveField(
            model_name="lordsdivisionvote",
            name="abstention",
        ),
        migrations.RemoveField(
            model_name="lordsdivisionvote",
            name="aye",
        ),
        migrations.RemoveField(
            model_name="lordsdivisionvote",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="lordsdivisionvote",
            name="did_not_vote",
        ),
        migrations.RemoveField(
            model_name="lordsdivisionvote",
            name="division",
        ),
        migrations.RemoveField(
            model_name="lordsdivisionvote",
            name="modified_on",
        ),
        migrations.RemoveField(
            model_name="lordsdivisionvote",
            name="no",
        ),
        migrations.RemoveField(
            model_name="lordsdivisionvote",
            name="person",
        ),
        migrations.RemoveField(
            model_name="lordsdivisionvote",
            name="suspended_or_expelled",
        ),
    ]
