# Generated by Django 3.2.4 on 2021-11-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0044_delete_lordsdivisionvote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LordsDivisionRedux',
            new_name='LordsDivision',
        ),
        migrations.RenameModel(
            old_name='LordsDivisionMemberVote',
            new_name='LordsDivisionVote',
        ),
    ]
