# Generated by Django 3.2.4 on 2021-12-07 14:18

from django.db import migrations, models

import util.models.generics
import util.time


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0046_auto_20211207_1416"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BillPublication",
        ),
        migrations.DeleteModel(
            name="BillSponsor",
        ),
        migrations.DeleteModel(
            name="BillStage",
        ),
        migrations.DeleteModel(
            name="BillStageSitting",
        ),
        migrations.DeleteModel(
            name="BillStageType",
        ),
        migrations.DeleteModel(
            name="BillType",
        ),
        migrations.DeleteModel(
            name="Bill",
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "parliamentdotuk",
                    models.PositiveIntegerField(
                        help_text="ID used on parliament.uk website",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, util.models.generics.BaseModelMixin),
        ),
    ]
