# Generated by Django 3.2.4 on 2022-02-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0047_auto_20220217_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpublicationlink',
            name='content_type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='billpublicationlink',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
