# Generated by Django 3.2.4 on 2022-02-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0048_auto_20220214_1838"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="bill_withdrawn",
            new_name="date_withdrawn",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="introduced_session",
            new_name="session_introduced",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="included_sessions",
            new_name="sessions",
        ),
        migrations.AddField(
            model_name="billstage",
            name="house",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="repository.house",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bill",
            name="summary",
            field=models.TextField(
                blank=True, help_text="HTML-formatted description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="billstage",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="repository.bill",
            ),
        ),
    ]
