# Generated by Django 3.2.4 on 2022-02-16 17:03

import django.db.models.deletion
from django.db import migrations, models

import util.models.generics
import util.time


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0049_auto_20220215_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPublication',
            fields=[
                ('created_on', models.DateTimeField(default=util.time.get_now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('parliamentdotuk', models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('display_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, util.models.generics.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='BillPublicationType',
            fields=[
                ('created_on', models.DateTimeField(default=util.time.get_now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('parliamentdotuk', models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, util.models.generics.BaseModelMixin),
        ),
        migrations.AlterField(
            model_name='bill',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billagent',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billstage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billstagetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='BillPublicationLink',
            fields=[
                ('created_on', models.DateTimeField(default=util.time.get_now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('parliamentdotuk', models.PositiveIntegerField(help_text='ID used on parliament.uk website', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('content_type', models.CharField(max_length=64)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='repository.billpublication')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, util.models.generics.BaseModelMixin),
        ),
        migrations.AddField(
            model_name='billpublication',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='repository.bill'),
        ),
        migrations.AddField(
            model_name='billpublication',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repository.house'),
        ),
        migrations.AddField(
            model_name='billpublication',
            name='publication_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='repository.billpublicationtype'),
        ),
    ]
