# Generated by Django 2.2.6 on 2019-11-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasknotification",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
