# Generated by Django 2.2.6 on 2019-11-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_tasknotification_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasknotification",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
