# Generated by Django 5.1.2 on 2024-10-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_alter_tasknotification_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasknotification",
            name="level",
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
