# Generated by Django 5.1.3 on 2024-11-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_alter_tasknotification_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasknotification",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="tasknotification",
            old_name="modified_on",
            new_name="modified_at",
        ),
    ]
