x-health: &health
  interval: 60s
  timeout: 10s
  start_period: 40s
  start_interval: 5s
  retries: 3

volumes:
    postgres_snommoc:
        name: postgres_snommoc

services:
  redis:
    image: redis:7-alpine
    healthcheck:
      test: redis-cli ping
      <<: *health

  postgres:
    image: postgis/postgis:17-3.5
    volumes:
      - postgres_snommoc:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      <<: *health

  django:
    healthcheck:
      test: curl --head --fail http://localhost:8000/api/ping/ || exit 1
      <<: *health

  next:
    healthcheck:
      test: curl --head --fail http://localhost:3000/health-check/ || exit 1
      <<: *health
    environment:
      API_BASE_URL: http://django:8000

  nginx:
    healthcheck:
      test: curl --head --fail http://localhost/health-check/ || exit 1
      <<: *health
