name: snommoc

x-common: &common
  env_file:
    - ".dev.env"
  restart: unless-stopped

x-dockerfile: &dockerfile
  dockerfile: ./docker/Dockerfile.dev
  context: .

x-health: &healthcheck
  start_period: 10s
  interval: 30s
  timeout: 5s
  retries: 5

volumes:
    postgres_snommoc:
        name: postgres_snommoc

services:
  postgres:
    <<: *common
    image: postgis/postgis:17-3.5
    container_name: snommoc_postgres
    volumes:
      - postgres_snommoc:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      <<: *healthcheck

  django: &django
    <<: *common
    container_name: snommoc_django
    build:
      <<: *dockerfile
      target: django
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/django:rw
      - ./runtime-dev:/tmp/runtime:rw
      - ./runtime-dev/log:/var/log/snommoc:rw
      - ./runtime-dev/media:/var/www/media:rw
      - ./runtime-dev/static:/var/www/static:rw
    healthcheck:
      test: curl --header --fail http://localhost:8000/api/ping/ || exit 1
      <<: *healthcheck

  django_manage:
    <<: *django
    container_name: snommoc_django_manage
    profiles:
      - "manage"
    ports: []
    volumes:
      - ./backend:/django:rw
      - ./runtime-dev:/tmp/runtime:rw
      - ./runtime-dev/log:/var/log/snommoc:rw
      - ./runtime-dev/media:/var/www/media:rw
      - ./runtime-dev/static:/var/www/static:rw
    healthcheck:
      test: ["NONE"]
    entrypoint: ["sh"]

  next:
    <<: *common
    container_name: snommoc_next
    build:
      <<: *dockerfile
      target: next
    depends_on:
      django:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    entrypoint: "npm run dev"
