BILL_SITTING_FORMAL = "formal"
BILL_SITTING_PROVISIONAL = "provisional"
BILL_TYPE = "type"
BILL_ACT_NAME = "act_name"
BILL_LABEL = "label"
BILL_HOMEPAGE = "homepage"
BILL_BALLOT_NUMBER = "ballot_number"
BILL_CHAPTER = "bill_chapter"
BILL_IS_PRIVATE = "is_private"
BILL_IS_MONEY_BILL = "is_money_bill"
BILL_PUBLIC_INVOLVEMENT_ALLOWED = "public_involvement_allowed"

BILL_SITTINGS = "sittings"
BILL_STAGES = "stages"
BILL_SPONSORS = "sponsors"
BILL_PUBLICATIONS = "publications"
