/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ping/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["api_urls_ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members */
        get: operations["api_routers_members_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{parliamentdotuk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Member */
        get: operations["api_routers_members_member"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{parliamentdotuk}/career/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Member Career */
        get: operations["api_routers_members_member_career"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{parliamentdotuk}/votes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Member Votes */
        get: operations["api_routers_members_member_votes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bills/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bills */
        get: operations["api_routers_bills_bills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bills/{parliamentdotuk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bill */
        get: operations["api_routers_bills_bill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constituencies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Constituencies
         * @description List of currently active constituencies
         */
        get: operations["api_routers_constituency_constituencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constituencies/{parliamentdotuk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Constituency */
        get: operations["api_routers_constituency_constituency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constituencies/{constituency_parliamentdotuk}/election/{election_parliamentdotuk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Constituency Election Result */
        get: operations["api_routers_constituency_constituency_election_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/divisions/commons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Commons Divisions */
        get: operations["api_routers_divisions_commons_divisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/divisions/commons/{parliamentdotuk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Commons Division */
        get: operations["api_routers_divisions_commons_division"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/divisions/lords/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lords Divisions */
        get: operations["api_routers_divisions_lords_divisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/divisions/lords/{parliamentdotuk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lords Division */
        get: operations["api_routers_divisions_lords_division"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/elections/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Elections */
        get: operations["api_routers_elections_elections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/elections/{parliamentdotuk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Election */
        get: operations["api_routers_elections_election"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parties/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parties */
        get: operations["api_routers_party_parties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parties/{parliamentdotuk}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Party */
        get: operations["api_routers_party_party"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zeitgeist/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Zeitgeist */
        get: operations["api_routers_zeitgeist_zeitgeist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        HouseType: "Commons" | "Lords";
        /** Input */
        Input: {
            /**
             * Limit
             * @default 24
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** ConstituencyMiniSchema */
        ConstituencyMiniSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            name: components["schemas"]["Name"];
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
        };
        /** MemberMiniSchema */
        MemberMiniSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            name: components["schemas"]["Name"];
            /** Current Posts */
            current_posts: string[];
            party: components["schemas"]["PartyMiniSchema"] | null;
            constituency: components["schemas"]["ConstituencyMiniSchema"] | null;
            /** Portrait */
            portrait?: string | null;
        };
        Name: string;
        /** PagedMemberMiniSchema */
        PagedMemberMiniSchema: {
            /** Items */
            items: components["schemas"]["MemberMiniSchema"][];
            /** Count */
            count: number;
        };
        ParliamentId: number;
        /** PartyMiniSchema */
        PartyMiniSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            name: components["schemas"]["Name"];
            /** Logo */
            logo: string | null;
            /** Logo Mask */
            logo_mask: string | null;
            theme: components["schemas"]["PartyThemeSchema"] | null;
            /** Active Member Count */
            active_member_count: number;
            /** Active Commons Members */
            active_commons_members?: number | null;
        };
        /** PartyThemeSchema */
        PartyThemeSchema: {
            /** Primary */
            primary: string;
            /** On Primary */
            on_primary: string;
            /** Accent */
            accent: string;
            /** On Accent */
            on_accent: string;
        };
        /** AddressSchema */
        AddressSchema: {
            /** Physical */
            physical: components["schemas"]["PhysicalAddressSchema"][];
            /** Web */
            web: components["schemas"]["WebAddressSchema"][];
        };
        /** CommitteeMemberSchema */
        CommitteeMemberSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            name: components["schemas"]["Name"];
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
        };
        EmailAddress: string;
        /** MemberProfile */
        MemberProfile: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            name: components["schemas"]["Name"];
            /** Current Posts */
            current_posts: string[];
            party: components["schemas"]["PartyMiniSchema"] | null;
            constituency: components["schemas"]["ConstituencyMiniSchema"] | null;
            portrait?: components["schemas"]["PortraitSchema"] | null;
            /** Full Title */
            full_title: string | null;
            given_name: components["schemas"]["Name"] | null;
            family_name: components["schemas"]["Name"] | null;
            status: components["schemas"]["MemberStatus"];
            /** House */
            house?: string | null;
            /** Date Of Birth */
            date_of_birth: string | null;
            /** Date Of Death */
            date_of_death: string | null;
            /** Age */
            age: number;
            /** Gender */
            gender: string | null;
            place_of_birth: components["schemas"]["TownSchema"] | null;
            /** Current Committees */
            current_committees: components["schemas"]["CommitteeMemberSchema"][];
            address: components["schemas"]["AddressSchema"];
            /** Subjects Of Interest */
            subjects_of_interest: components["schemas"]["SubjectOfInterestSchema"][];
            wikipedia: components["schemas"]["WikipediaPath"] | null;
        };
        /** MemberStatus */
        MemberStatus: {
            /** Is Current */
            is_current: boolean;
            /** Is Active */
            is_active: boolean;
            /** Description */
            description: string | null;
            /** Extra Notes */
            extra_notes: string | null;
            /** Since */
            since: string | null;
        };
        PhoneNumber: string;
        /** PhysicalAddressSchema */
        PhysicalAddressSchema: {
            /** Description */
            description?: string | null;
            /** Address */
            address?: string | null;
            /** Postcode */
            postcode?: string | null;
            phone: components["schemas"]["PhoneNumber"] | null;
            fax: components["schemas"]["PhoneNumber"] | null;
            email?: components["schemas"]["EmailAddress"] | null;
        };
        /** PortraitSchema */
        PortraitSchema: {
            /** Full */
            full?: string | null;
            /** Square */
            square?: string | null;
            /** Wide */
            wide?: string | null;
            /** Tall */
            tall?: string | null;
        };
        /** SubjectOfInterestSchema */
        SubjectOfInterestSchema: {
            /** Category */
            category: string;
            /** Description */
            description: string;
        };
        /** TownSchema */
        TownSchema: {
            town: components["schemas"]["Name"];
            country: components["schemas"]["Name"];
        };
        Url: string;
        /** WebAddressSchema */
        WebAddressSchema: {
            url: components["schemas"]["Url"];
            /** Description */
            description: string | null;
        };
        WikipediaPath: string;
        /** ConstituencyRepresentation */
        ConstituencyRepresentation: {
            constituency: components["schemas"]["ConstituencyMiniSchema"];
            /**
             * Start
             * Format: date
             */
            start: string;
            /** End */
            end: string | null;
        };
        /** DeclaredInterestsSchema */
        DeclaredInterestsSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            /** Category */
            category: string | null;
            /** Description */
            description: string | null;
            /** Created */
            created: string | null;
            /** Amended */
            amended: string | null;
            /** Deleted */
            deleted: string | null;
            /** Registered Late */
            registered_late: boolean;
        };
        /** ExperienceSchema */
        ExperienceSchema: {
            /** Category */
            category: string | null;
            /** Organisation */
            organisation: string | null;
            /** Title */
            title: string | null;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
        };
        /** HouseMembershipSchema */
        HouseMembershipSchema: {
            house: components["schemas"]["Name"];
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
        };
        /** MemberCareerHistory */
        MemberCareerHistory: {
            /** Posts */
            posts: components["schemas"]["PostSchema"][];
            /** Parties */
            parties: components["schemas"]["PartyAffiliationSchema"][];
            /** Constituencies */
            constituencies: components["schemas"]["ConstituencyRepresentation"][];
            /** Committees */
            committees: components["schemas"]["CommitteeMemberSchema"][];
            /** Experiences */
            experiences: components["schemas"]["ExperienceSchema"][];
            /** Houses */
            houses: components["schemas"]["HouseMembershipSchema"][];
            /** Interests */
            interests: components["schemas"]["DeclaredInterestsSchema"][];
        };
        /** PartyAffiliationSchema */
        PartyAffiliationSchema: {
            party: components["schemas"]["PartyMiniSchema"];
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
        };
        /** PostSchema */
        PostSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            /** Type */
            type: string;
            name: components["schemas"]["Name"];
            /** Hansard */
            hansard: string | null;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
        };
        /** DivisionMiniSchema */
        DivisionMiniSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            /** Title */
            title: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            house: components["schemas"]["HouseType"];
            /** Is Passed */
            is_passed: boolean;
        };
        /** MemberVotesSchema */
        MemberVotesSchema: {
            /** Commons */
            commons: components["schemas"]["VoteSchema"][];
            /** Lords */
            lords: components["schemas"]["VoteSchema"][];
        };
        /** VoteSchema */
        VoteSchema: {
            division: components["schemas"]["DivisionMiniSchema"];
            /** Vote */
            vote: string;
        };
        /** BillMiniSchema */
        BillMiniSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Last Update
             * Format: date-time
             */
            last_update: string;
        };
        /** PagedBillMiniSchema */
        PagedBillMiniSchema: {
            /** Items */
            items: components["schemas"]["BillMiniSchema"][];
            /** Count */
            count: number;
        };
        /** BillFullSchema */
        BillFullSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            type: components["schemas"]["BillType"];
            /**
             * Last Update
             * Format: date-time
             */
            last_update: string;
            /** Is Act */
            is_act: boolean;
            /** Is Defeated */
            is_defeated: boolean;
            /** Date Withdrawn */
            date_withdrawn?: string | null;
            /** Sponsors */
            sponsors: components["schemas"]["Sponsor"][];
            /** Publications */
            publications: components["schemas"]["Publication"][];
            session_introduced: components["schemas"]["Session"];
            /** Sessions */
            sessions: components["schemas"]["Session"][];
            current_stage: components["schemas"]["Stage"] | null;
            /** Stages */
            stages: components["schemas"]["Stage"][];
        };
        /** BillType */
        BillType: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            /** Category */
            category: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** Publication */
        Publication: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            /** Title */
            title: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Type */
            type: string;
            /** Links */
            links: components["schemas"]["PublicationLink"][];
        };
        /** PublicationLink */
        PublicationLink: {
            /** Title */
            title: string;
            url: components["schemas"]["Url"];
            /** Content Type */
            content_type: string;
        };
        /** Session */
        Session: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            /** Name */
            name: string | null;
        };
        /** Sponsor */
        Sponsor: {
            /** Id */
            id: number;
            profile?: components["schemas"]["MemberMiniSchema"] | null;
            organisation: components["schemas"]["SponsorOrganisation"] | null;
        };
        /** SponsorOrganisation */
        SponsorOrganisation: {
            /** Name */
            name: string;
            url: components["schemas"]["Url"];
        };
        /** Stage */
        Stage: {
            /** Sittings */
            sittings: string[];
            session: components["schemas"]["Session"];
            house: components["schemas"]["HouseType"];
            /** Latest Sitting */
            latest_sitting: string | null;
        };
        /** PagedConstituencyMiniSchema */
        PagedConstituencyMiniSchema: {
            /** Items */
            items: components["schemas"]["ConstituencyMiniSchema"][];
            /** Count */
            count: number;
        };
        /** ConstituencyFullSchema */
        ConstituencyFullSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            name: components["schemas"]["Name"];
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            mp: components["schemas"]["MemberMiniSchema"] | null;
            /** Boundary */
            boundary?: Record<string, never> | null;
            /** Results */
            results: components["schemas"]["ResultsSchema"][];
        };
        /** ElectionSchema */
        ElectionSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            name: components["schemas"]["Name"];
            /** Date */
            date: string | null;
            /** Election Type */
            election_type: string;
        };
        /** ResultsSchema */
        ResultsSchema: {
            election: components["schemas"]["ElectionSchema"];
            mp: components["schemas"]["MemberMiniSchema"] | null;
        };
        /** ConstituencyCandidateSchema */
        ConstituencyCandidateSchema: {
            name: components["schemas"]["Name"];
            profile?: components["schemas"]["MemberMiniSchema"] | null;
            party: components["schemas"]["PartyMiniSchema"] | null;
            /** Order */
            order: number;
            /** Votes */
            votes: number;
        };
        /** ConstituencyResultSchema */
        ConstituencyResultSchema: {
            /** Electorate */
            electorate: number;
            /** Turnout */
            turnout: number;
            /** Result */
            result: string;
            /** Majority */
            majority: number;
            constituency: components["schemas"]["ConstituencyMiniSchema"];
            election: components["schemas"]["ElectionSchema"];
            /** Candidates */
            candidates: components["schemas"]["ConstituencyCandidateSchema"][];
        };
        /** PagedDivisionMiniSchema */
        PagedDivisionMiniSchema: {
            /** Items */
            items: components["schemas"]["DivisionMiniSchema"][];
            /** Count */
            count: number;
        };
        /** CommonsDivisionSchema */
        CommonsDivisionSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            /** Title */
            title: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            house: components["schemas"]["HouseType"];
            /** Is Passed */
            is_passed: boolean;
            /** Is Deferred Vote */
            is_deferred_vote: boolean;
            /** Ayes */
            ayes: number;
            /** Noes */
            noes: number;
            /** Did Not Vote */
            did_not_vote: number;
            /** Votes */
            votes: components["schemas"]["CommonsVoteSchema"][];
        };
        /** CommonsVoteSchema */
        CommonsVoteSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            name: components["schemas"]["Name"];
            /** Vote */
            vote: string;
            party: components["schemas"]["PartyMiniSchema"];
        };
        /** LordsDivisionSchema */
        LordsDivisionSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            /** Title */
            title: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            house: components["schemas"]["HouseType"];
            /** Description */
            description: string | null;
            sponsor?: components["schemas"]["MemberMiniSchema"] | null;
            /** Is Passed */
            is_passed: boolean;
            /** Is Whipped Vote */
            is_whipped_vote: boolean;
            /** Ayes */
            ayes: number;
            /** Noes */
            noes: number;
            /** Votes */
            votes: components["schemas"]["LordsVoteSchema"][];
        };
        /** LordsVoteSchema */
        LordsVoteSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            name: components["schemas"]["Name"];
            /** Vote */
            vote: string;
            party: components["schemas"]["PartyMiniSchema"];
        };
        /** PagedElectionSchema */
        PagedElectionSchema: {
            /** Items */
            items: components["schemas"]["ElectionSchema"][];
            /** Count */
            count: number;
        };
        /** PagedPartyMiniSchema */
        PagedPartyMiniSchema: {
            /** Items */
            items: components["schemas"]["PartyMiniSchema"][];
            /** Count */
            count: number;
        };
        /** GenderDemographics */
        GenderDemographics: {
            /**
             * Modified At
             * Format: date-time
             */
            modified_at: string;
            /** House */
            house: string;
            /** Male Member Count */
            male_member_count: number;
            /** Female Member Count */
            female_member_count: number;
            /** Non Binary Member Count */
            non_binary_member_count: number;
            /** Total Member Count */
            total_member_count: number;
        };
        /** LordsDemographics */
        LordsDemographics: {
            /**
             * Modified At
             * Format: date-time
             */
            modified_at: string;
            /** Life Count */
            life_count: number;
            /** Hereditary Count */
            hereditary_count: number;
            /** Bishop Count */
            bishop_count: number;
            /** Total Count */
            total_count: number;
        };
        /** PartyFullSchema */
        PartyFullSchema: {
            parliamentdotuk: components["schemas"]["ParliamentId"];
            name: components["schemas"]["Name"];
            short_name: components["schemas"]["Name"] | null;
            long_name: components["schemas"]["Name"] | null;
            homepage: components["schemas"]["Url"] | null;
            /** Year Founded */
            year_founded: number | null;
            wikipedia: components["schemas"]["WikipediaPath"] | null;
            /** Logo */
            logo: string | null;
            /** Logo Mask */
            logo_mask: string | null;
            /** Active Member Count */
            active_member_count: number;
            /** Gender Demographics */
            gender_demographics: components["schemas"]["GenderDemographics"][];
            lords_demographics?: components["schemas"]["LordsDemographics"] | null;
            theme: components["schemas"]["PartyThemeSchema"] | null;
        };
        /** Motd */
        Motd: {
            /** Title */
            title: string | null;
            /** Description */
            description: string | null;
            action_url: components["schemas"]["Url"] | null;
        };
        /** ZeitgeistItem[BillMiniSchema] */
        ZeitgeistItem_BillMiniSchema_: {
            /** Priority */
            priority: number;
            /** Reason */
            reason: string;
            target: components["schemas"]["BillMiniSchema"];
        };
        /** ZeitgeistItem[DivisionMiniSchema] */
        ZeitgeistItem_DivisionMiniSchema_: {
            /** Priority */
            priority: number;
            /** Reason */
            reason: string;
            target: components["schemas"]["DivisionMiniSchema"];
        };
        /** ZeitgeistItem[MemberMiniSchema] */
        ZeitgeistItem_MemberMiniSchema_: {
            /** Priority */
            priority: number;
            /** Reason */
            reason: string;
            target: components["schemas"]["MemberMiniSchema"];
        };
        /** ZeitgeistSchema */
        ZeitgeistSchema: {
            /** Motd */
            motd: components["schemas"]["Motd"][];
            /** People */
            people: components["schemas"]["ZeitgeistItem_MemberMiniSchema_"][];
            /** Divisions */
            divisions: components["schemas"]["ZeitgeistItem_DivisionMiniSchema_"][];
            /** Bills */
            bills: components["schemas"]["ZeitgeistItem_BillMiniSchema_"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_urls_ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_members_members: {
        parameters: {
            query?: {
                query?: string;
                party?: number;
                house?: components["schemas"]["HouseType"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedMemberMiniSchema"];
                };
            };
        };
    };
    api_routers_members_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parliamentdotuk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberProfile"];
                };
            };
        };
    };
    api_routers_members_member_career: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parliamentdotuk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberCareerHistory"];
                };
            };
        };
    };
    api_routers_members_member_votes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parliamentdotuk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberVotesSchema"];
                };
            };
        };
    };
    api_routers_bills_bills: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedBillMiniSchema"];
                };
            };
        };
    };
    api_routers_bills_bill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parliamentdotuk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillFullSchema"];
                };
            };
        };
    };
    api_routers_constituency_constituencies: {
        parameters: {
            query?: {
                query?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedConstituencyMiniSchema"];
                };
            };
        };
    };
    api_routers_constituency_constituency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parliamentdotuk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstituencyFullSchema"];
                };
            };
        };
    };
    api_routers_constituency_constituency_election_result: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                constituency_parliamentdotuk: number;
                election_parliamentdotuk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstituencyResultSchema"];
                };
            };
        };
    };
    api_routers_divisions_commons_divisions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedDivisionMiniSchema"];
                };
            };
        };
    };
    api_routers_divisions_commons_division: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parliamentdotuk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommonsDivisionSchema"];
                };
            };
        };
    };
    api_routers_divisions_lords_divisions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedDivisionMiniSchema"];
                };
            };
        };
    };
    api_routers_divisions_lords_division: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parliamentdotuk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LordsDivisionSchema"];
                };
            };
        };
    };
    api_routers_elections_elections: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedElectionSchema"];
                };
            };
        };
    };
    api_routers_elections_election: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parliamentdotuk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectionSchema"];
                };
            };
        };
    };
    api_routers_party_parties: {
        parameters: {
            query?: {
                query?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedPartyMiniSchema"];
                };
            };
        };
    };
    api_routers_party_party: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parliamentdotuk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartyFullSchema"];
                };
            };
        };
    };
    api_routers_zeitgeist_zeitgeist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZeitgeistSchema"];
                };
            };
        };
    };
}
