SNOMMOC = "SNOMMOC"
SOCIAL = "SOCIAL"
CACHE = "CACHE"

CACHE_CRAWLER_TTL = "CRAWLER_CACHE_TTL"
CACHE_WIKI_TTL = "WIKI_CACHE_TTL"
CRAWLER_CACHE_ROOT = "CRAWLER_CACHE_ROOT"

SOCIAL_USERNAME_BLOCKED_EXACT = "USERNAME_BLOCKED_EXACT"
SOCIAL_USERNAME_BLOCKED_SUBSTRINGS = "USERNAME_BLOCKED_SUBSTRINGS"

AUTH = "AUTH"
AUTH_API_READ_REQUIRES_AUTH = "API_READ_REQUIRES_AUTH"
