LORDS_DIVISION_DATA = {
    "divisionId": 2613,
    "date": "2021-11-16T00:00:00",
    "number": 2,
    "notes": None,
    "title": "Dormant Assets Bill [HL]",
    "isWhipped": True,
    "isGovernmentContent": False,
    "authoritativeContentCount": 164,
    "authoritativeNotContentCount": 192,
    "divisionHadTellers": False,
    "tellerContentCount": 164,
    "tellerNotContentCount": 192,
    "memberContentCount": 164,
    "memberNotContentCount": 192,
    "sponsoringMemberId": 1557,
    "isHouse": True,
    "amendmentMotionNotes": "<p>Baroness Kramer moved amendment 6, in clause 29, page 22, line 20, at end to insert—<br />“(3A) An order under this section may not be made unless the Secretary of State has certified that dormant account money will be used to fund projects, or aspects of project, for which funds would be unlikely to be made available by a Government department.”<br />The House divided:</p>",
    "isGovernmentWin": True,
    "remoteVotingStart": "2021-11-16T17:49:37",
    "remoteVotingEnd": "2021-11-16T17:59:37",
    "divisionWasExclusivelyRemote": True,
    "contentTellers": [],
    "notContentTellers": [],
    "contents": [
        {
            "memberId": 457,
            "name": "Lord Pendry",
            "listAs": "Pendry, L.",
            "memberFrom": "Life peer",
            "party": "Labour",
            "partyColour": "ff0000",
            "partyAbbreviation": "Lab",
            "partyIsMainParty": True,
        },
        {
            "memberId": 2758,
            "name": "Lord Falconer of Thoroton",
            "listAs": "Falconer of Thoroton, L.",
            "memberFrom": "Life peer",
            "party": "Labour",
            "partyColour": "ff0000",
            "partyAbbreviation": "Lab",
            "partyIsMainParty": True,
        },
        {
            "memberId": 395,
            "name": "Lord Blunkett",
            "listAs": "Blunkett, L.",
            "memberFrom": "Life peer",
            "party": "Labour",
            "partyColour": "ff0000",
            "partyAbbreviation": "Lab",
            "partyIsMainParty": True,
        },
    ],
    "notContents": [
        {
            "memberId": 3329,
            "name": "Lord Brougham and Vaux",
            "listAs": "Brougham and Vaux, L.",
            "memberFrom": "Excepted Hereditary",
            "party": "Conservative",
            "partyColour": "0000ff",
            "partyAbbreviation": "Con",
            "partyIsMainParty": True,
        },
        {
            "memberId": 3799,
            "name": "Lord James of Blackheath",
            "listAs": "James of Blackheath, L.",
            "memberFrom": "Life peer",
            "party": "Conservative",
            "partyColour": "0000ff",
            "partyAbbreviation": "Con",
            "partyIsMainParty": True,
        },
    ],
}
