"""

"""

import logging

import uuid as uuid
from django.db import models
from notifications import permissions

log = logging.getLogger(__name__)


class TaskNotification(models.Model):
    class Meta:
        permissions = [
            (permissions.VIEW_NOTIFICATION,
             'Can view notifications generated by tasks'),
            (permissions.DISMISS_NOTIFICATION,
             'Can dismiss notifications generated by tasks')
        ]

    title = models.CharField(max_length=80, blank=True, null=True)
    content = models.TextField(null=True, blank=True)
    uuid = models.UUIDField(default=uuid.uuid4)
    read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)

    @classmethod
    def create(cls, content: str, title: str = 'Task notification'):
        n = TaskNotification.objects.create(content=content, title=title)
        n.save()
        return n

    def __str__(self):
        return f'{self.title}: {self.content}'
