ARG PYTHON_VERSION=3.12

################################################################################
FROM python:${PYTHON_VERSION}-alpine AS django
ENV PYTHONBUFFERED 1

RUN apk add curl

# GeoDjango requirements
RUN apk add \
    gcc \
    libc-dev \
    geos-dev \
    binutils \
    proj \
    geos \
    gdal \
    && if [ ! -e /usr/lib/libproj.so ]; then ln -s /usr/lib/libproj.so.* /usr/lib/libproj.so; fi \
    || if [ ! -e /usr/lib/libgdal.so ]; then ln -s /usr/lib/libgdal.so.* /usr/lib/libgdal.so; fi \
    || if [ ! -e /usr/lib/libgeos_c.so ]; then ln -s /usr/lib/libgeos_c.so.* /usr/lib/libgeos_c.so; fi

WORKDIR /django/
COPY ../backend/requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

EXPOSE 8000
COPY ./docker/django-entrypoint.dev.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

################################################################################
FROM node:23-alpine AS next

WORKDIR /frontend/
