"""Test data for MDP schemas"""

"""A JSON response containing a full member biography."""
MemberFullBiog = {
    "Members": {
        "Member": {
            "@Member_Id": "4514",
            "@Dods_Id": "75589",
            "@Pims_Id": "6161",
            "@Clerks_Id": "1408",
            "DisplayAs": "Sir Keir Starmer",
            "ListAs": "Starmer, Sir Keir",
            "FullTitle": "Rt Hon Sir Keir Starmer MP",
            "LayingMinisterName": "The Prime Minister",
            "DateOfBirth": {
                "@xsi:nil": "true",
                "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            },
            "DateOfDeath": {
                "@xsi:nil": "true",
                "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            },
            "Gender": "M",
            "Party": {"@Id": "15", "#text": "Labour"},
            "House": "Commons",
            "MemberFrom": "Holborn and St Pancras",
            "HouseStartDate": "2015-05-07T00:00:00",
            "HouseEndDate": {
                "@xsi:nil": "true",
                "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            },
            "CurrentStatus": {
                "@Id": "0",
                "@IsActive": "True",
                "Name": "Current Member",
                "Reason": None,
                "StartDate": "2024-07-04T00:00:00",
            },
            "BasicDetails": {
                "GivenSurname": "Starmer",
                "GivenMiddleNames": None,
                "GivenForename": "Keir",
                "TownOfBirth": None,
                "CountryOfBirth": None,
                "Gender": "M",
                "DateOfBirth": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "DateOfRetirement": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "DateOfDeath": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "LordsDetails": None,
            },
            "PreferredNames": {
                "PreferredName": [
                    {
                        "Title": "Sir",
                        "Surname": "Starmer",
                        "MiddleNames": None,
                        "Forename": "Keir",
                        "Suffix": None,
                        "AddressAs": None,
                        "Note": None,
                        "StartDate": "2024-07-09T00:00:00",
                        "EndDate": {
                            "@xsi:nil": "true",
                            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                        },
                        "ListAs": "Starmer, Sir Keir",
                        "DisplayAs": "Sir Keir Starmer",
                        "FullTitle": "Rt Hon Sir Keir Starmer MP",
                        "HonouraryPrefixes": {
                            "HonouraryPrefix": {"Name": "Right Honourable"}
                        },
                    },
                    {
                        "Title": None,
                        "Surname": "Starmer",
                        "MiddleNames": None,
                        "Forename": "Keir",
                        "Suffix": None,
                        "AddressAs": "Keir Starmer",
                        "Note": None,
                        "StartDate": "2017-07-19T00:00:00",
                        "EndDate": "2024-07-09T00:00:00",
                        "ListAs": "Starmer, Keir",
                        "DisplayAs": "Keir Starmer",
                        "FullTitle": "Rt Hon Keir Starmer",
                        "HonouraryPrefixes": {
                            "HonouraryPrefix": {"Name": "Right Honourable"}
                        },
                    },
                    {
                        "Title": None,
                        "Surname": "Starmer",
                        "MiddleNames": None,
                        "Forename": "Keir",
                        "Suffix": None,
                        "AddressAs": "Keir Starmer",
                        "Note": "Created at General Election",
                        "StartDate": "2015-05-07T00:00:00",
                        "EndDate": "2017-07-19T00:00:00",
                        "ListAs": "Starmer, Keir",
                        "DisplayAs": "Keir Starmer",
                        "FullTitle": "Keir Starmer",
                        "HonouraryPrefixes": None,
                    },
                ]
            },
            "HouseMemberships": {
                "HouseMembership": {
                    "House": "Commons",
                    "StartDate": "2015-05-07T00:00:00",
                    "EndDate": {
                        "@xsi:nil": "true",
                        "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                    },
                    "EndReason": None,
                    "EndNotes": None,
                }
            },
            "Constituencies": {
                "Constituency": [
                    {
                        "@Id": "4105",
                        "Name": "Holborn and St Pancras",
                        "StartDate": "2024-07-04T00:00:00",
                        "EndDate": {
                            "@xsi:nil": "true",
                            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                        },
                        "Election": {
                            "@Id": "422",
                            "Name": "2024 General Election",
                            "Date": "2024-07-04T00:00:00",
                            "Type": "General Election",
                        },
                        "EndReason": None,
                        "EntryType": "Continuation",
                        "Notes": "Created at General Election",
                        "SwearInOrder": None,
                        "SwornInForename": None,
                        "SwornInMiddleNames": None,
                        "SwornInSurname": None,
                        "SwornInTitle": None,
                    },
                    {
                        "@Id": "3536",
                        "Name": "Holborn and St Pancras",
                        "StartDate": "2019-12-12T00:00:00",
                        "EndDate": "2024-05-30T00:00:00",
                        "Election": {
                            "@Id": "397",
                            "Name": "2019 General Election",
                            "Date": "2019-12-12T00:00:00",
                            "Type": "General Election",
                        },
                        "EndReason": "Dissolution",
                        "EntryType": "Continuation",
                        "Notes": "Created at General Election",
                        "SwearInOrder": None,
                        "SwornInForename": None,
                        "SwornInMiddleNames": None,
                        "SwornInSurname": None,
                        "SwornInTitle": None,
                    },
                    {
                        "@Id": "3536",
                        "Name": "Holborn and St Pancras",
                        "StartDate": "2017-06-08T00:00:00",
                        "EndDate": "2019-11-06T00:00:00",
                        "Election": {
                            "@Id": "377",
                            "Name": "2017 General Election",
                            "Date": "2017-06-08T00:00:00",
                            "Type": "General Election",
                        },
                        "EndReason": "Dissolution",
                        "EntryType": "Continuation",
                        "Notes": "Created at General Election",
                        "SwearInOrder": None,
                        "SwornInForename": None,
                        "SwornInMiddleNames": None,
                        "SwornInSurname": None,
                        "SwornInTitle": None,
                    },
                    {
                        "@Id": "3536",
                        "Name": "Holborn and St Pancras",
                        "StartDate": "2015-05-07T00:00:00",
                        "EndDate": "2017-05-03T00:00:00",
                        "Election": {
                            "@Id": "369",
                            "Name": "2015 General Election",
                            "Date": "2015-05-07T00:00:00",
                            "Type": "General Election",
                        },
                        "EndReason": "Dissolution",
                        "EntryType": "First entry",
                        "Notes": None,
                        "SwearInOrder": None,
                        "SwornInForename": None,
                        "SwornInMiddleNames": None,
                        "SwornInSurname": None,
                        "SwornInTitle": None,
                    },
                ]
            },
            "ElectionsContested": None,
            "MaidenSpeeches": {
                "MaidenSpeech": {
                    "House": "Commons",
                    "SpeechDate": "2015-05-28T00:00:00",
                    "Hansard": "596 c254-7",
                    "Subject": "Debate on the Address (2nd Day)",
                }
            },
            "Committees": {
                "Committee": {
                    "@Id": "83",
                    "Name": "Home Affairs Committee",
                    "StartDate": "2015-07-08T00:00:00",
                    "EndDate": "2015-10-26T00:00:00",
                    "EndNote": None,
                    "IsExOfficio": "False",
                    "IsAlternate": "False",
                    "IsCoOpted": "False",
                    "ChairDates": None,
                }
            },
            "GovernmentPosts": {
                "GovernmentPost": {
                    "@Id": "1267",
                    "Name": "Prime Minister and First Lord of the Treasury",
                    "HansardName": "The Prime Minister",
                    "StartDate": "2024-07-05T00:00:00",
                    "EndDate": None,
                    "Note": None,
                    "EndNote": None,
                    "IsJoint": "False",
                    "IsUnpaid": "False",
                    "Email": None,
                    "LayingMinisterName": "The Prime Minister",
                }
            },
            "OppositionPosts": {
                "OppositionPost": [
                    {
                        "@Id": "4",
                        "Name": "Leader of HM Official Opposition",
                        "HansardName": "Leader of HM Official Opposition",
                        "StartDate": "2020-04-04T00:00:00",
                        "EndDate": "2024-07-05T00:00:00",
                        "Note": None,
                        "EndNote": None,
                        "IsJoint": "False",
                        "IsUnpaid": "False",
                        "Email": None,
                    },
                    {
                        "@Id": "1315",
                        "Name": "Shadow Secretary of State for Exiting the European Union",
                        "HansardName": "Shadow Secretary of State for Exiting the European Union",
                        "StartDate": "2016-10-06T00:00:00",
                        "EndDate": "2020-04-04T00:00:00",
                        "Note": None,
                        "EndNote": None,
                        "IsJoint": "False",
                        "IsUnpaid": "False",
                        "Email": None,
                    },
                    {
                        "@Id": "884",
                        "Name": "Shadow Minister (Home Office)",
                        "HansardName": "Shadow Minister (Home Office)",
                        "StartDate": "2015-09-18T00:00:00",
                        "EndDate": "2016-06-27T00:00:00",
                        "Note": None,
                        "EndNote": None,
                        "IsJoint": "False",
                        "IsUnpaid": "False",
                        "Email": None,
                    },
                ]
            },
            "ParliamentaryPosts": {
                "ParliamentaryPost": {
                    "@Id": "789",
                    "Name": "Leader of the Labour Party",
                    "HansardName": None,
                    "StartDate": "2020-04-04T00:00:00",
                    "EndDate": None,
                    "Note": None,
                    "EndNote": None,
                    "IsJoint": "False",
                    "IsUnpaid": "False",
                    "Email": None,
                    "LayingMinisterName": None,
                }
            },
            "Statuses": {
                "Status": [
                    {
                        "@Id": "0",
                        "Name": "Current Member",
                        "StartDate": "2024-07-04T00:00:00",
                        "EndDate": {
                            "@xsi:nil": "true",
                            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                        },
                    },
                    {
                        "@Id": "0",
                        "Name": "Current Member",
                        "StartDate": "2019-12-12T00:00:00",
                        "EndDate": "2024-05-30T00:00:00",
                    },
                    {
                        "@Id": "0",
                        "Name": "Current Member",
                        "StartDate": "2017-06-08T00:00:00",
                        "EndDate": "2019-11-06T00:00:00",
                    },
                    {
                        "@Id": "0",
                        "Name": "Current Member",
                        "StartDate": "2015-05-07T00:00:00",
                        "EndDate": "2017-05-03T00:00:00",
                    },
                ]
            },
            "Parties": {
                "Party": [
                    {
                        "@Id": "15",
                        "Name": "Labour",
                        "SubType": None,
                        "StartDate": "2024-07-04T00:00:00",
                        "EndDate": {
                            "@xsi:nil": "true",
                            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                        },
                        "Note": "Created at General Election",
                        "SitsOppositeSideToParty": "False",
                    },
                    {
                        "@Id": "15",
                        "Name": "Labour",
                        "SubType": None,
                        "StartDate": "2019-12-12T00:00:00",
                        "EndDate": "2024-05-30T00:00:00",
                        "Note": "Dissolution of Parliament",
                        "SitsOppositeSideToParty": "False",
                    },
                    {
                        "@Id": "15",
                        "Name": "Labour",
                        "SubType": None,
                        "StartDate": "2017-06-08T00:00:00",
                        "EndDate": "2019-11-06T00:00:00",
                        "Note": "Dissolution of Parliament",
                        "SitsOppositeSideToParty": "False",
                    },
                    {
                        "@Id": "15",
                        "Name": "Labour",
                        "SubType": None,
                        "StartDate": "2015-05-07T00:00:00",
                        "EndDate": "2017-05-03T00:00:00",
                        "Note": "Dissolution of Parliament",
                        "SitsOppositeSideToParty": "False",
                    },
                ]
            },
            "Honours": {
                "Honour": [
                    {
                        "@Id": "40",
                        "Name": "PC",
                        "HonourList": None,
                        "StartDate": "2017-07-19T00:00:00",
                        "EndDate": {
                            "@xsi:nil": "true",
                            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                        },
                        "Note": None,
                    },
                    {
                        "@Id": "25",
                        "Name": "KCB",
                        "HonourList": "New Year's",
                        "StartDate": "2014-01-01T00:00:00",
                        "EndDate": {
                            "@xsi:nil": "true",
                            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                        },
                        "Note": "2014 honours list",
                    },
                ]
            },
            "OtherParliaments": None,
            "Interests": None,
            "Staffing": None,
            "Addresses": {
                "Address": [
                    {
                        "@Type_Id": "1",
                        "Type": "Parliamentary office",
                        "IsPreferred": "False",
                        "IsPhysical": "True",
                        "Note": None,
                        "Address1": "House of Commons",
                        "Address2": "London",
                        "Address3": None,
                        "Address4": None,
                        "Address5": None,
                        "Postcode": "SW1A 0AA",
                        "Phone": None,
                        "Fax": None,
                        "Email": "keir.starmer.mp@parliament.uk",
                        "OtherAddress": None,
                    },
                    {
                        "@Type_Id": "7",
                        "Type": "X (formerly Twitter)",
                        "IsPreferred": "False",
                        "IsPhysical": "False",
                        "Note": None,
                        "Address1": "https://twitter.com/keir_starmer",
                    },
                    {
                        "@Type_Id": "6",
                        "Type": "Website",
                        "IsPreferred": "False",
                        "IsPhysical": "False",
                        "Note": None,
                        "Address1": "http://www.keirstarmer.com/",
                    },
                    {
                        "@Type_Id": "4",
                        "Type": "Constituency office",
                        "IsPreferred": "False",
                        "IsPhysical": "True",
                        "Note": None,
                        "Address1": "Constituency Office",
                        "Address2": None,
                        "Address3": None,
                        "Address4": None,
                        "Address5": None,
                        "Postcode": None,
                        "Phone": None,
                        "Fax": None,
                        "Email": "keir.starmer.constituency@parliament.uk",
                        "OtherAddress": None,
                    },
                    {
                        "@Type_Id": "1009",
                        "Type": "Prime Minister's office",
                        "IsPreferred": "False",
                        "IsPhysical": "False",
                        "Note": None,
                        "Address1": "https://contact.no10.gov.uk/",
                    },
                ]
            },
            "KnownAs": None,
            "BiographyEntries": None,
            "Experiences": None,
        }
    }
}

"""A JSON response containing a list of member summaries"""
MemberList = {
    "Members": {
        "Member": [
            {
                "@Member_Id": "172",
                "@Dods_Id": "25790",
                "@Pims_Id": "3572",
                "@Clerks_Id": "1",
                "DisplayAs": "Ms Diane Abbott",
                "ListAs": "Abbott, Ms Diane",
                "FullTitle": "Rt Hon Diane Abbott MP",
                "LayingMinisterName": None,
                "DateOfBirth": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "DateOfDeath": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "Gender": "F",
                "Party": {"@Id": "15", "#text": "Labour"},
                "House": "Commons",
                "MemberFrom": "Hackney North and Stoke Newington",
                "HouseStartDate": "1987-06-11T00:00:00",
                "HouseEndDate": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "CurrentStatus": {
                    "@Id": "0",
                    "@IsActive": "True",
                    "Name": "Current Member",
                    "Reason": None,
                    "StartDate": "2024-07-04T00:00:00",
                },
            },
            {
                "@Member_Id": "5131",
                "@Dods_Id": "109725",
                "@Pims_Id": "6547",
                "@Clerks_Id": "",
                "DisplayAs": "Jack Abbott",
                "ListAs": "Abbott, Jack",
                "FullTitle": "Jack Abbott MP",
                "LayingMinisterName": None,
                "DateOfBirth": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "DateOfDeath": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "Gender": "M",
                "Party": {"@Id": "15", "#text": "Labour (Co-op)"},
                "House": "Commons",
                "MemberFrom": "Ipswich",
                "HouseStartDate": "2024-07-04T00:00:00",
                "HouseEndDate": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "CurrentStatus": {
                    "@Id": "0",
                    "@IsActive": "True",
                    "Name": "Current Member",
                    "Reason": None,
                    "StartDate": "2024-07-04T00:00:00",
                },
            },
            {
                "@Member_Id": "4212",
                "@Dods_Id": "80556",
                "@Pims_Id": "5905",
                "@Clerks_Id": "5905",
                "DisplayAs": "Debbie Abrahams",
                "ListAs": "Abrahams, Debbie",
                "FullTitle": "Debbie Abrahams MP",
                "LayingMinisterName": None,
                "DateOfBirth": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "DateOfDeath": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "Gender": "F",
                "Party": {"@Id": "15", "#text": "Labour"},
                "House": "Commons",
                "MemberFrom": "Oldham East and Saddleworth",
                "HouseStartDate": "2011-01-13T00:00:00",
                "HouseEndDate": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "CurrentStatus": {
                    "@Id": "0",
                    "@IsActive": "True",
                    "Name": "Current Member",
                    "Reason": None,
                    "StartDate": "2024-07-04T00:00:00",
                },
            },
            {
                "@Member_Id": "662",
                "@Dods_Id": "",
                "@Pims_Id": "",
                "@Clerks_Id": "",
                "DisplayAs": "Leo Abse",
                "ListAs": "Abse, Leo",
                "FullTitle": "Leo Abse",
                "LayingMinisterName": None,
                "DateOfBirth": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "DateOfDeath": "2008-08-19T00:00:00",
                "Gender": "M",
                "Party": {"@Id": "15", "#text": "Labour"},
                "House": "Commons",
                "MemberFrom": "Torfaen",
                "HouseStartDate": "1958-11-10T00:00:00",
                "HouseEndDate": "1987-06-11T00:00:00",
                "CurrentStatus": {
                    "@Id": "",
                    "@IsActive": "False",
                    "Name": None,
                    "Reason": None,
                    "StartDate": {
                        "@xsi:nil": "true",
                        "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                    },
                },
            },
            {
                "@Member_Id": "5120",
                "@Dods_Id": "174942",
                "@Pims_Id": "6536",
                "@Clerks_Id": "",
                "DisplayAs": "Shockat Adam",
                "ListAs": "Adam, Shockat",
                "FullTitle": "Shockat Adam MP",
                "LayingMinisterName": None,
                "DateOfBirth": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "DateOfDeath": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "Gender": "M",
                "Party": {"@Id": "8", "#text": "Independent"},
                "House": "Commons",
                "MemberFrom": "Leicester South",
                "HouseStartDate": "2024-07-04T00:00:00",
                "HouseEndDate": {
                    "@xsi:nil": "true",
                    "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
                },
                "CurrentStatus": {
                    "@Id": "0",
                    "@IsActive": "True",
                    "Name": "Current Member",
                    "Reason": None,
                    "StartDate": "2024-07-04T00:00:00",
                },
            },
        ]
    }
}
