SNOMMOC = "SNOMMOC"
SOCIAL = "SOCIAL"
CACHE = "CACHE"

CACHE_CRAWLER_TTL = "CRAWLER_CACHE_TTL"
CACHE_WIKI_TTL = "WIKI_CACHE_TTL"

SOCIAL_USERNAME_BLOCKED_EXACT = "USERNAME_BLOCKED_EXACT"
SOCIAL_USERNAME_BLOCKED_SUBSTRINGS = "USERNAME_BLOCKED_SUBSTRINGS"
