# Generated by Django 3.2.4 on 2021-11-24 15:43

import django.db.models.deletion
from django.db import migrations, models

import util.time


class Migration(migrations.Migration):

    replaces = [
        ("surface", "0001_initial"),
        ("surface", "0002_featuredcommonsdivision_featuredlordsdivision"),
        ("surface", "0003_messageoftheday"),
        ("surface", "0004_auto_20200820_1823"),
        ("surface", "0005_zeitgeistitem"),
        ("surface", "0006_auto_20210426_1554"),
        ("surface", "0007_auto_20210902_1733"),
        ("surface", "0008_alter_featuredlordsdivision_target"),
    ]

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("repository", "0018_person_current_post"),
        ("repository", "0043_create_lordsdivisionredux"),
        ("repository", "0014_auto_20200316_2026"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedBill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="repository.bill",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeaturedCommonsDivision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="repository.commonsdivision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeaturedPerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="repository.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageOfTheDay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("title", models.CharField(max_length=512)),
                ("description", models.CharField(max_length=1024)),
                ("action_url", models.URLField(blank=True, null=True)),
                ("display", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Message Of The Day",
                "verbose_name_plural": "MOTDs",
            },
        ),
        migrations.CreateModel(
            name="ZeitgeistItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("target_id", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[("feature", "feature"), ("social", "social")],
                        max_length=24,
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=50)),
            ],
            options={
                "verbose_name": "Zeitgeist item",
                "verbose_name_plural": "Zeitgeist items",
                "unique_together": {("target_id", "target_type")},
            },
        ),
        migrations.CreateModel(
            name="FeaturedLordsDivision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="repository.lordsdivisionredux",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
