# Generated by Django 3.0.2 on 2020-05-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0002_featuredcommonsdivision_featuredlordsdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Message Of The Day',
                'verbose_name_plural': 'MOTDs',
            },
        ),
    ]
