# Generated by Django 3.0.7 on 2020-09-10 16:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('surface', '0004_auto_20200820_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeitgeistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('target_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('feature', 'feature'), ('social', 'social')], max_length=24)),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Zeitgeist item',
                'verbose_name_plural': 'Zeitgeist items',
                'unique_together': {('target_id', 'target_type')},
            },
        ),
    ]
