# Generated by Django 3.2.4 on 2021-11-23 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0044_delete_lordsdivisionvote"),
        ("surface", "0007_auto_20210902_1733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredlordsdivision",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="repository.lordsdivisionredux",
            ),
        ),
    ]
