# Generated by Django 3.2.4 on 2021-11-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0040_auto_20211118_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lordsdivision',
            name='description',
            field=models.TextField(),
        ),
    ]
