# Generated by Django 3.2.4 on 2021-11-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0043_create_lordsdivisionredux"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LordsDivisionVote",
        ),
        migrations.DeleteModel(
            name="LordsDivision",
        ),
    ]
