# Generated by Django 3.2.4 on 2022-03-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0048_auto_20220222_1706'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='billsponsor',
            constraint=models.UniqueConstraint(fields=('bill', 'member', 'organisation'), name='unique_billsponsor_per_bill'),
        ),
    ]
