# Generated by Django 5.1.2 on 2024-11-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0050_alter_billstagesitting_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commonsdivisionvote",
            options={"ordering": ["-modified_on"]},
        ),
        migrations.RemoveConstraint(
            model_name="lordsdivisionvote",
            name="One vote per Person per LordsDivision",
        ),
        migrations.AddField(
            model_name="commonsdivisionvote",
            name="vote_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="repository.divisionvotetype",
            ),
        ),
        migrations.AlterField(
            model_name="commonsdivisionvote",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commons_votes",
                to="repository.person",
            ),
        ),
        migrations.AlterField(
            model_name="lordsdivisionvote",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="repository.lordsdivision",
            ),
        ),
        migrations.AlterField(
            model_name="lordsdivisionvote",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lords_votes",
                to="repository.person",
            ),
        ),
        migrations.AlterField(
            model_name="lordsdivisionvote",
            name="vote_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="repository.divisionvotetype",
            ),
        ),
        migrations.AddConstraint(
            model_name="commonsdivisionvote",
            constraint=models.UniqueConstraint(
                fields=("person", "division"),
                name="One vote per person per repository.CommonsDivision",
            ),
        ),
        migrations.AddConstraint(
            model_name="lordsdivisionvote",
            constraint=models.UniqueConstraint(
                fields=("person", "division"),
                name="One vote per person per repository.LordsDivision",
            ),
        ),
    ]
