# Generated by Django 5.1.2 on 2024-11-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0051_alter_commonsdivisionvote_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commonsdivisionvote",
            name="abstention",
        ),
        migrations.RemoveField(
            model_name="commonsdivisionvote",
            name="aye",
        ),
        migrations.RemoveField(
            model_name="commonsdivisionvote",
            name="did_not_vote",
        ),
        migrations.RemoveField(
            model_name="commonsdivisionvote",
            name="no",
        ),
        migrations.RemoveField(
            model_name="commonsdivisionvote",
            name="suspended_or_expelled",
        ),
    ]
