# Generated by Django 5.1.3 on 2024-11-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0053_alter_partytheme_accent_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="party_logo"),
        ),
    ]
