# Generated by Django 5.1.3 on 2024-11-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0054_party_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="party_logo"),
        ),
    ]
