# Generated by Django 5.1.3 on 2024-11-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0055_alter_party_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="logo_mask",
            field=models.FileField(blank=True, null=True, upload_to="party_logo_mask"),
        ),
    ]
