# Generated by Django 5.1.3 on 2024-11-20 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0056_party_logo_mask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="constituency",
        ),
        migrations.AlterField(
            model_name="constituency",
            name="mp",
            field=models.OneToOneField(
                help_text="Current representative",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="repository.person",
            ),
        ),
    ]
