# Generated by Django 5.1.3 on 2024-11-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0057_fix_constituency_mp_duplicated_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="constituency",
            name="constituency_type",
        ),
        migrations.AlterField(
            model_name="constituency",
            name="gss_code",
            field=models.CharField(
                blank=True,
                help_text="Government Statistical Service ID",
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
    ]
