# Generated by Django 5.1.3 on 2024-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0058_remove_constituency_type_and_unique_gss_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="constituencyboundary",
            name="area",
        ),
        migrations.RemoveField(
            model_name="constituencyboundary",
            name="boundary_kml",
        ),
        migrations.RemoveField(
            model_name="constituencyboundary",
            name="boundary_length",
        ),
        migrations.RemoveField(
            model_name="constituencyboundary",
            name="center_latitude",
        ),
        migrations.RemoveField(
            model_name="constituencyboundary",
            name="center_longitude",
        ),
        migrations.AddField(
            model_name="constituencyboundary",
            name="geo_json",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
