# Generated by Django 5.1.3 on 2024-11-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0060_recreate_constituencyresultdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partytheme",
            name="accent",
            field=models.CharField(
                default="#ffffff", help_text="Hex color code", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="partytheme",
            name="on_accent",
            field=models.CharField(
                choices=[("#ffffff", "light"), ("#000000", "dark")],
                default="#000000",
                help_text="Color for text that overlays accent",
                max_length=10,
            ),
        ),
    ]
