# Generated by Django 5.1.3 on 2024-11-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0061_alter_partytheme_accent_alter_partytheme_on_accent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="active",
            new_name="is_active",
        ),
        migrations.AlterField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether this person currently has a seat in parliament.",
            ),
        ),
        migrations.RemoveField(
            model_name="person",
            name="date_entered_house",
        ),
        migrations.RemoveField(
            model_name="person",
            name="date_left_house",
        ),
    ]
