# Generated by Django 5.1.3 (and edited) on 2024-11-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0062_rename_person_active_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ParliamentaryPost",
            new_name="OtherPost",
        ),
        migrations.RenameModel(
            old_name="GovernmentPostMember", new_name="GovernmentPostHolder"
        ),
        migrations.RenameModel(
            old_name="OppositionPostMember", new_name="OppositionPostHolder"
        ),
        migrations.RenameModel(
            old_name="ParliamentaryPostMember", new_name="OtherPostHolder"
        ),
        migrations.AlterField(
            model_name="governmentpostholder",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holders",
                to="repository.governmentpost",
            ),
        ),
        migrations.AlterField(
            model_name="oppositionpostholder",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holders",
                to="repository.oppositionpost",
            ),
        ),
        migrations.AlterField(
            model_name="otherpostholder",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holders",
                to="repository.otherpost",
            ),
        ),
    ]
