# Generated by Django 5.1.3 on 2024-11-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0064_post_postholder_simplification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="current_post",
        ),
    ]
