# Generated by Django 5.1.3 on 2024-11-22 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0066_constituencyrepresentative"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestedelection",
            name="election",
        ),
        migrations.AddField(
            model_name="contestedelection",
            name="date",
            field=models.DateField(default=datetime.date(1, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="committeemember",
            constraint=models.UniqueConstraint(
                fields=("person", "committee", "start"),
                name="unique_committee_per_person_per_start_date",
            ),
        ),
    ]
