# Generated by Django 5.1.3 on 2024-11-22 16:00

import django.db.models.deletion
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0067_remove_contestedelection_election_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressType",
            fields=[
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "parliamentdotuk",
                    models.PositiveIntegerField(
                        help_text="ID used on parliament.uk website",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model,),
        ),
        migrations.RemoveField(
            model_name="physicaladdress",
            name="description",
        ),
        migrations.RemoveField(
            model_name="webaddress",
            name="description",
        ),
        migrations.AddField(
            model_name="physicaladdress",
            name="is_preferred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="webaddress",
            name="is_preferred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="physicaladdress",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="repository.addresstype",
            ),
        ),
        migrations.AddField(
            model_name="webaddress",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="repository.addresstype",
            ),
        ),
        migrations.AddConstraint(
            model_name="physicaladdress",
            constraint=models.UniqueConstraint(
                fields=("type", "person"), name="unique_address_type_per_person"
            ),
        ),
        migrations.AddConstraint(
            model_name="webaddress",
            constraint=models.UniqueConstraint(
                fields=("type", "person"), name="unique_webaddress_type_per_person"
            ),
        ),
    ]
