# Generated by Django 5.1.3 on 2024-11-22 16:58

import django.db.models.deletion
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0068_addresstype_remove_physicaladdress_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Experience"),
        migrations.DeleteModel(name="ExperienceCategory"),
        migrations.CreateModel(
            name="ExperienceCategory",
            fields=[
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "parliamentdotuk",
                    models.PositiveIntegerField(
                        help_text="ID used on parliament.uk website",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name_plural": "Experience categories",
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "parliamentdotuk",
                    models.PositiveIntegerField(
                        help_text="ID used on parliament.uk website",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "organisation",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("title", models.CharField(max_length=512)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.person",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.experiencecategory",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "title", "start"),
                        name="unique_title_per_person_per_startdate",
                    )
                ],
            },
            bases=(models.Model,),
        ),
    ]
