# Generated by Django 5.1.3 on 2024-11-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0069_recreate_experience_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declaredinterest",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_interests",
                to="repository.person",
            ),
        ),
    ]
