# Generated by Django 5.1.3 on 2024-11-23 15:07

import django.db.models.deletion
import util.models.generics
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0070_alter_declaredinterest_person"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeclaredInterestCategory",
        ),
        migrations.DeleteModel(
            name="DeclaredInterest",
        ),
        migrations.CreateModel(
            name="RegisteredInterestCategory",
            fields=[
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "parliamentdotuk",
                    models.PositiveIntegerField(
                        help_text="ID used on parliament.uk website",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=512)),
            ],
            options={
                "verbose_name_plural": "Registered interest categories",
            },
            bases=(models.Model, util.models.generics.BaseModelMixin),
        ),
        migrations.CreateModel(
            name="RegisteredInterest",
            fields=[
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "parliamentdotuk",
                    models.PositiveIntegerField(
                        help_text="ID used on parliament.uk website",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                ("created", models.DateField(blank=True, null=True)),
                ("amended", models.DateField(blank=True, null=True)),
                ("deleted", models.DateField(blank=True, null=True)),
                ("is_correction", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="repository.registeredinterest",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_interests",
                        to="repository.person",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.registeredinterestcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, util.models.generics.BaseModelMixin),
        ),
    ]
