# Generated by Django 5.1.3 on 2024-11-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0071_recreate_registeredinterest_models"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subjectofinterest",
            old_name="subject",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="subjectofinterest",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="subjectofinterest",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects_of_interest",
                to="repository.person",
            ),
        ),
        migrations.AlterField(
            model_name="subjectofinterestcategory",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
