# Generated by Django 5.1.3 on 2024-11-23 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0072_rename_subjectofinterest_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="repository.person",
            ),
        ),
        migrations.AlterField(
            model_name="experiencecategory",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
