# Generated by Django 5.1.3 on 2024-11-23 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0073_alter_experience_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physicaladdress",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="physical_addresses",
                to="repository.person",
            ),
        ),
        migrations.AlterField(
            model_name="webaddress",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="web_addresses",
                to="repository.person",
            ),
        ),
    ]
