# Generated by Django 5.1.3 on 2024-11-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0074_alter_physicaladdress_person_alter_webaddress_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemember",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committees",
                to="repository.person",
            ),
        ),
    ]
