# Generated by Django 5.1.3 on 2024-11-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0075_alter_committeemember_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housemembership",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to="repository.person",
            ),
        ),
    ]
