# Generated by Django 5.1.3 on 2024-11-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0077_alter_constituencyrepresentative_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestedelection",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contested_elections",
                to="repository.person",
            ),
        ),
    ]
