# Generated by Django 5.1.3 on 2024-11-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0079_alter_personalsoknownas_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="additional_info",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="additional_info_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
