# Generated by Django 5.1.3 on 2024-11-24 13:45

import django.db.models.deletion
import util.models.generics
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0080_post_additional_info_post_additional_info_link"),
    ]

    operations = [
        migrations.RenameModel("PartyAssociation", "PartyAffiliation"),
        migrations.AlterField(
            model_name="partyaffiliation",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="party_affiliations",
                to="repository.person",
            ),
        ),
    ]
