# Generated by Django 5.1.3 on 2024-11-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0081_rename_model_partyassociation_partyaffiliation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housemembership",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_memberships",
                to="repository.person",
            ),
        ),
    ]
