# Generated by Django 5.1.3 on 2024-11-24 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0082_alter_housemembership_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="repository.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="name",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
