# Generated by Django 5.1.3 on 2024-11-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0083_alter_experience_organisation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physicaladdress",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
