# Generated by Django 5.1.3 on 2024-11-24 16:43

import django.db.models.deletion
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0084_alter_physicaladdress_address"),
    ]

    operations = [
        migrations.DeleteModel(name="RegisteredInterest"),
        migrations.CreateModel(
            name="RegisteredInterest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "parliamentdotuk",
                    models.PositiveIntegerField(
                        help_text="ID used on parliament.uk website - unique per RegisteredInterestCategory"
                    ),
                ),
                ("description", models.TextField()),
                ("created", models.DateField(blank=True, null=True)),
                ("amended", models.DateField(blank=True, null=True)),
                ("deleted", models.DateField(blank=True, null=True)),
                ("is_correction", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.registeredinterestcategory",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="repository.registeredinterest",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_interests",
                        to="repository.person",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parliamentdotuk", "category"),
                        name="unique_id_per_category",
                    )
                ],
            },
            bases=(models.Model,),
        ),
    ]
