# Generated by Django 5.1.3 on 2024-11-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0085_recreate_registeredinterest"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="experience",
            name="unique_title_per_person_per_startdate",
        ),
        migrations.AddConstraint(
            model_name="experience",
            constraint=models.UniqueConstraint(
                fields=("person", "title", "organisation", "start"),
                name="unique_title_per_person_per_startdate",
            ),
        ),
    ]
