# Generated by Django 5.1.3 on 2024-11-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "repository",
            "0086_remove_experience_unique_title_per_person_per_startdate_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registeredinterest",
            name="unique_id_per_category",
        ),
        migrations.AlterField(
            model_name="registeredinterest",
            name="parliamentdotuk",
            field=models.PositiveIntegerField(
                help_text="ID used on parliament.uk website - unique per person"
            ),
        ),
        migrations.AddConstraint(
            model_name="registeredinterest",
            constraint=models.UniqueConstraint(
                fields=("parliamentdotuk", "person"), name="unique_id_per_person"
            ),
        ),
    ]
