# Generated by Django 5.1.3 on 2024-11-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0088_remove_experience_unique_title_per_person_per_startdate"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="constituencyresult",
            name="unique_constituency_result",
        ),
        migrations.RenameField(
            model_name="constituencyresult",
            old_name="mp",
            new_name="winner",
        ),
        migrations.AlterField(
            model_name="constituencyresult",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constituency_results",
                related_query_name="constituency_result",
                to="repository.person",
            ),
        ),
        migrations.AddField(
            model_name="constituencyresult",
            name="winner_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="constituencycandidate",
            name="election_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                related_query_name="candidate",
                to="repository.constituencyresultdetail",
            ),
        ),
        migrations.AlterField(
            model_name="constituencyrepresentative",
            name="constituency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="representatives",
                related_query_name="representative",
                to="repository.constituency",
            ),
        ),
        migrations.AddConstraint(
            model_name="constituencyrepresentative",
            constraint=models.UniqueConstraint(
                fields=("person", "constituency", "start"),
                name="unique_person_per_constituency_per_startdate",
            ),
        ),
        migrations.AddConstraint(
            model_name="constituencyresult",
            constraint=models.UniqueConstraint(
                fields=("election", "constituency"), name="unique_constituency_result"
            ),
        ),
        migrations.DeleteModel(
            name="ConstituencyAlsoKnownAs",
        ),
        migrations.DeleteModel(
            name="UnlinkedConstituency",
        ),
    ]
