# Generated by Django 5.1.3 on 2024-11-25 14:55

import django.db.models.deletion
import util.models.generics
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0089_remove_constituencyalsoknownas_canonical_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="is_active",
        ),
        migrations.CreateModel(
            name="PersonStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField()),
                ("description", models.CharField(blank=True, max_length=64, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="repository.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, util.models.generics.BaseModelMixin),
        ),
    ]
