# Generated by Django 5.1.3 on 2024-11-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0090_remove_person_is_active_personstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personstatus",
            name="is_active",
            field=models.BooleanField(db_index=True),
        ),
    ]
