# Generated by Django 5.1.3 on 2024-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0092_alter_commonsdivisionvote_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commonsdivision",
            name="abstentions",
        ),
        migrations.RemoveField(
            model_name="commonsdivision",
            name="errors",
        ),
        migrations.RemoveField(
            model_name="commonsdivision",
            name="non_eligible",
        ),
        migrations.RemoveField(
            model_name="commonsdivision",
            name="suspended_or_expelled",
        ),
        migrations.RemoveField(
            model_name="commonsdivision",
            name="uin",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="division_was_exclusively_remote",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="remote_voting_end",
        ),
        migrations.RemoveField(
            model_name="lordsdivision",
            name="remote_voting_start",
        ),
        migrations.AddField(
            model_name="commonsdivision",
            name="is_passed",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lordsdivision",
            name="is_passed",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commonsdivision",
            name="did_not_vote",
            field=models.PositiveSmallIntegerField(
                help_text="How many members did not vote at all"
            ),
        ),
    ]
