# Generated by Django 5.1.3 on 2024-11-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0093_remove_commonsdivision_abstentions_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commonsdivision",
            old_name="deferred_vote",
            new_name="is_deferred_vote",
        ),
    ]
