# Generated by Django 5.1.3 on 2024-11-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0094_rename_deferred_vote_commonsdivision_is_deferred_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonsdivisionvote",
            name="is_teller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lordsdivisionvote",
            name="is_teller",
            field=models.BooleanField(default=False),
        ),
    ]
