# Generated by Django 5.1.3 on 2024-11-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0095_commonsdivisionvote_is_teller_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="current_stage",
        ),
    ]
