# Generated by Django 5.1.3 on 2024-11-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0096_remove_bill_current_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constituencyboundary",
            name="constituency",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boundary",
                to="repository.constituency",
            ),
        ),
    ]
