# Generated by Django 5.1.3 on 2024-11-28 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0097_alter_constituencyboundary_constituency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constituencyresult",
            name="constituency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                related_query_name="result",
                to="repository.constituency",
            ),
        ),
        migrations.AlterField(
            model_name="constituencyresult",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                related_query_name="result",
                to="repository.election",
            ),
        ),
    ]
