# Generated by Django 5.1.3 on 2024-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0098_alter_constituencyresult_constituency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="constituencycandidate",
            name="party_name",
        ),
        migrations.AddField(
            model_name="constituencycandidate",
            name="result_change",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
