# Generated by Django 5.1.3 on 2024-11-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0099_remove_constituencycandidate_party_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constituency",
            name="mp",
            field=models.OneToOneField(
                help_text="Current representative",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="constituency",
                to="repository.person",
            ),
        ),
    ]
