# Generated by Django 5.1.3 on 2024-11-29 11:36

import django.db.models.deletion
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0100_alter_constituency_mp"),
    ]

    operations = [
        migrations.CreateModel(
            name="LordsDemographics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=util.time.get_now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("life_count", models.PositiveSmallIntegerField()),
                ("hereditary_count", models.PositiveSmallIntegerField()),
                ("bishop_count", models.PositiveSmallIntegerField()),
                ("total_count", models.PositiveSmallIntegerField()),
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lords_demographics",
                        to="repository.party",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartyDemographics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=util.time.get_now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("male_member_count", models.PositiveSmallIntegerField()),
                ("female_member_count", models.PositiveSmallIntegerField()),
                ("non_binary_member_count", models.PositiveSmallIntegerField()),
                ("total_member_count", models.PositiveSmallIntegerField()),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demographics",
                        to="repository.house",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demographics",
                        to="repository.party",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("party", "house"),
                        name="unique_demographics_per_party_per_house",
                    )
                ],
            },
        ),
    ]
