# Generated by Django 5.1.3 on 2024-11-29 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0101_lordsdemographics_partydemographics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="lords_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The source of this person's lordship, if applicable (e.g. hereditary, bishop, peerage, etc)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lords",
                related_query_name="lord",
                to="repository.lordstype",
            ),
        ),
    ]
