# Generated by Django 5.1.3 on 2024-12-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0102_alter_person_lords_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="active_member_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
