# Generated by Django 5.1.3 on 2024-12-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0103_party_active_member_count"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PartyDemographics",
            new_name="PartyGenderDemographics",
        ),
        migrations.RenameModel(
            old_name="LordsDemographics",
            new_name="PartyLordsDemographics",
        ),
        migrations.RemoveConstraint(
            model_name="partygenderdemographics",
            name="unique_demographics_per_party_per_house",
        ),
        migrations.AddConstraint(
            model_name="partygenderdemographics",
            constraint=models.UniqueConstraint(
                fields=("party", "house"),
                name="unique_gender_demographics_per_party_per_house",
            ),
        ),
    ]
