# Generated by Django 5.1.3 on 2024-12-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0106_alter_partyaffiliation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="sort_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
