# Generated by Django 5.1.3 on 2024-12-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0107_person_sort_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personstatus",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
