# Generated by Django 5.1.3 on 2024-12-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0108_alter_personstatus_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="personstatus",
            name="is_current",
            field=models.BooleanField(db_index=True, default=False),
            preserve_default=False,
        ),
    ]
