# Generated by Django 5.1.3 on 2024-12-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0109_personstatus_is_current"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personstatus",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                help_text="Whether this person is currently using their seat. May be false if they are on leave or suspended in some way.",
            ),
        ),
        migrations.AlterField(
            model_name="personstatus",
            name="is_current",
            field=models.BooleanField(
                db_index=True,
                help_text="Whether this person currently has a seat in one of the houses.",
            ),
        ),
    ]
