# Generated by Django 5.1.3 on 2024-12-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0110_alter_personstatus_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="party",
            field=models.ForeignKey(
                blank=True,
                help_text="Current party membership. Historic memberships can be retrieved via PartyAffiliation model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="repository.party",
            ),
        ),
    ]
