# Generated by Django 5.1.3 on 2024-12-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0111_alter_person_party"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="additional_name",
        ),
        migrations.RemoveField(
            model_name="person",
            name="family_name",
        ),
        migrations.RemoveField(
            model_name="person",
            name="given_name",
        ),
    ]
