# Generated by Django 5.1.3 on 2024-12-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0112_remove_person_additional_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="constituency",
            name="ascii_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Simplified ASCII name",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="ascii_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Simplified ASCII name",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="ascii_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Simplified ASCII name",
                max_length=128,
                null=True,
            ),
        ),
    ]
