# Generated by Django 5.1.3 on 2024-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0113_constituency_ascii_name_party_ascii_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partytheme",
            name="rgb_accent",
            field=models.CharField(
                default="255 255 255", editable=False, max_length=16
            ),
        ),
        migrations.AddField(
            model_name="partytheme",
            name="rgb_on_accent",
            field=models.CharField(default="0 0 0", editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name="partytheme",
            name="rgb_on_primary",
            field=models.CharField(
                default="255 255 255", editable=False, max_length=16
            ),
        ),
        migrations.AddField(
            model_name="partytheme",
            name="rgb_primary",
            field=models.CharField(default="0 0 0", editable=False, max_length=16),
        ),
    ]
