# Generated by Django 5.1.3 on 2024-12-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0114_partytheme_rgb_accent_partytheme_rgb_on_accent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="election",
            options={"ordering": ["-date"]},
        ),
    ]
