# Generated by Django 5.1.3 on 2024-12-19 15:38

import django.db.models.deletion
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0115_alter_election_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="post",
        ),
        migrations.DeleteModel(
            name="postholder",
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=util.time.get_now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "parliamentdotuk",
                    models.PositiveIntegerField(
                        help_text="ID used on parliament.uk website"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("government", "Government"),
                            ("opposition", "Opposition"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                (
                    "hansard_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "additional_info",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("additional_info_link", models.URLField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parliamentdotuk", "type"),
                        name="unique_parliamentdotuk_per_posttype",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PostHolder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=util.time.get_now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="repository.person",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holders",
                        to="repository.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
