# Generated by Django 5.1.3 on 2024-12-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0116_recreate_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postholder",
            options={"ordering": ["-end", "-start"]},
        ),
    ]
