# Generated by Django 5.1.3 on 2024-12-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0117_alter_postholder_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committeemember",
            options={"ordering": ["-end", "-start"]},
        ),
        migrations.AlterModelOptions(
            name="constituencyrepresentative",
            options={"ordering": ["-end", "-start"]},
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["-end", "-start"]},
        ),
        migrations.AlterModelOptions(
            name="partyaffiliation",
            options={"ordering": ["-end", "-start"]},
        ),
        migrations.AlterModelOptions(
            name="registeredinterest",
            options={"ordering": ["-amended", "-created"]},
        ),
    ]
