# Generated by Django 5.1.3 on 2025-01-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0119_recreate_registeredinterestcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredinterest",
            name="description_data",
            field=models.JSONField(default=dict),
        ),
    ]
