# Generated by Django 5.1.3 on 2025-02-04 11:38

import django.db.models.deletion
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0120_registeredinterest_description_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimplifiedConstituencyBoundary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=util.time.get_now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("geo_json", models.JSONField()),
                (
                    "constituency",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simple_boundary",
                        to="repository.constituency",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Simplified Constituency Boundaries",
            },
        ),
    ]
