# Generated by Django 5.1.6 on 2025-02-07 17:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0121_simplifiedconstituencyboundary"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstituencyBoundaryGIS",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=util.time.get_now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, tolerance=1
                    ),
                ),
                ("north", models.FloatField()),
                ("south", models.FloatField()),
                ("east", models.FloatField()),
                ("west", models.FloatField()),
                ("centroid", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("simple_json", models.TextField()),
                (
                    "constituency",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boundary_gis",
                        to="repository.constituency",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="SimplifiedConstituencyBoundary",
        ),
    ]
