# Generated by Django 5.1.6 on 2025-02-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0122_constituencyboundarygis_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="constituencyboundarygis",
            options={"verbose_name_plural": "Constituency Boundaries"},
        ),
        migrations.AlterField(
            model_name="constituencyboundarygis",
            name="constituency",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boundary",
                to="repository.constituency",
            ),
        ),
        migrations.DeleteModel(
            name="ConstituencyBoundary",
        ),
    ]
