# Generated by Django 5.1.6 on 2025-02-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0123_alter_constituencyboundarygis_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConstituencyBoundaryGIS",
            new_name="ConstituencyBoundary",
        ),
    ]
