# Generated by Django 5.1.6 on 2025-02-11 13:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0125_partyterritory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constituencyboundary",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                srid=4326, tolerance=1
            ),
        ),
        migrations.AlterField(
            model_name="partyterritory",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                srid=4326, tolerance=1
            ),
        ),
    ]
