# Generated by Django 5.1.6 on 2025-06-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0127_remove_partytheme_rgb_accent_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="CommonsDivisionVote"),
        migrations.DeleteModel(name="CommonsDivision"),
        migrations.DeleteModel(name="LordsDivisionVote"),
        migrations.DeleteModel(name="LordsDivision"),
    ]
