# Generated by Django 5.2.3 on 2025-06-28 16:56

import django.db.models.deletion
import repository.models.mixins
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0128_recreate_divisions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParliamentaryEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=util.time.get_now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "parliamentaryevent_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="repository.parliamentaryevent",
                    ),
                ),
                (
                    "parliamentdotuk",
                    models.PositiveIntegerField(
                        help_text="ID used on parliament.uk website"
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("is_passed", models.BooleanField()),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "ayes",
                    models.PositiveSmallIntegerField(
                        help_text="How many members voted for the motion"
                    ),
                ),
                (
                    "noes",
                    models.PositiveSmallIntegerField(
                        help_text="How many members voted against the motion"
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.house",
                    ),
                ),
            ],
            bases=(
                "repository.parliamentaryevent",
                repository.models.mixins.SocialMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CommonsDivision",
            fields=[
                (
                    "division_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="repository.division",
                    ),
                ),
                (
                    "did_not_vote",
                    models.PositiveSmallIntegerField(
                        help_text="How many members did not vote at all"
                    ),
                ),
                (
                    "is_deferred_vote",
                    models.BooleanField(
                        default=False,
                        help_text="A deferred vote is one that is not held immediately at the end of the debate, but at a later 'convenient' time",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="repository.parliamentarysession",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("repository.division", models.Model),
        ),
        migrations.CreateModel(
            name="LordsDivision",
            fields=[
                (
                    "division_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="repository.division",
                    ),
                ),
                ("amendment_motion_notes", models.TextField(blank=True, null=True)),
                ("is_whipped", models.BooleanField()),
                ("is_government_content", models.BooleanField()),
                ("division_had_tellers", models.BooleanField()),
                ("teller_content_count", models.PositiveSmallIntegerField()),
                ("teller_not_content_count", models.PositiveSmallIntegerField()),
                ("is_government_win", models.BooleanField(blank=True, null=True)),
                (
                    "sponsoring_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_lords_divisions",
                        to="repository.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("repository.division", models.Model),
        ),
        migrations.CreateModel(
            name="DivisionVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=util.time.get_now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_teller", models.BooleanField(default=False)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="repository.person",
                    ),
                ),
                (
                    "vote_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="repository.divisionvotetype",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="repository.division",
                    ),
                ),
            ],
            options={
                "ordering": ["-division__date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "division"),
                        name="One vote per person per division",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="division",
            constraint=models.UniqueConstraint(
                fields=("parliamentdotuk", "house"), name="Unique id per house"
            ),
        ),
    ]
