# Generated by Django 5.2.3 on 2025-07-09 15:44

import util.time
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0129_parliamentaryevent_division_commonsdivision_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="organisation"),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=util.time.get_now)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "companies_house_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
