# Generated by Django 5.2.3 on 2025-07-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0130_organisation_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billstage',
            options={'ordering': ['-sittings__date']},
        ),
    ]
