# Generated by Django 5.2.3 on 2025-07-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0131_alter_billstage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='active_member_count',
        ),
    ]
