# Generated by Django 5.2.3 on 2025-08-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0001_squashed_0132_cleanup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billpublicationtype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
