# Generated by Django 3.0.2 on 2020-03-16 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0014_auto_20200316_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=240)),
                ('flagged', models.BooleanField(default=False, help_text='Somebody has flagged this commment for review')),
                ('visible', models.BooleanField(default=True, help_text='This comment may be displayed publicly')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='BaseLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonLike',
            fields=[
                ('baselike_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.BaseLike')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=('social.baselike',),
        ),
        migrations.CreateModel(
            name='PersonComment',
            fields=[
                ('basecomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.BaseComment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=('social.basecomment',),
        ),
        migrations.CreateModel(
            name='LordsDivisionLike',
            fields=[
                ('baselike_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.BaseLike')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.LordsDivision')),
            ],
            options={
                'abstract': False,
            },
            bases=('social.baselike',),
        ),
        migrations.CreateModel(
            name='LordsDivisionComment',
            fields=[
                ('basecomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.BaseComment')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.LordsDivision')),
            ],
            options={
                'abstract': False,
            },
            bases=('social.basecomment',),
        ),
        migrations.CreateModel(
            name='CommonsDivisionLike',
            fields=[
                ('baselike_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.BaseLike')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.CommonsDivision')),
            ],
            options={
                'abstract': False,
            },
            bases=('social.baselike',),
        ),
        migrations.CreateModel(
            name='CommonsDivisionComment',
            fields=[
                ('basecomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.BaseComment')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.CommonsDivision')),
            ],
            options={
                'abstract': False,
            },
            bases=('social.basecomment',),
        ),
        migrations.CreateModel(
            name='BillLike',
            fields=[
                ('baselike_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.BaseLike')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Bill')),
            ],
            options={
                'abstract': False,
            },
            bases=('social.baselike',),
        ),
        migrations.CreateModel(
            name='BillComment',
            fields=[
                ('basecomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='social.BaseComment')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Bill')),
            ],
            options={
                'abstract': False,
            },
            bases=('social.basecomment',),
        ),
    ]
