# Generated by Django 3.0.2 on 2020-06-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social', '0004_auto_20200414_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('target_id', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=240)),
                ('flagged', models.BooleanField(default=False, help_text='Somebody has flagged this comment for review')),
                ('visible', models.BooleanField(default=True, help_text='This comment may be displayed publicly')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='social.UserToken')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('target_id', models.PositiveIntegerField()),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='social.UserToken')),
            ],
        ),
        migrations.CreateModel(
            name='VoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='billcomment',
            name='basecomment_ptr',
        ),
        migrations.RemoveField(
            model_name='billcomment',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billlike',
            name='baselike_ptr',
        ),
        migrations.RemoveField(
            model_name='billlike',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='commonsdivisioncomment',
            name='basecomment_ptr',
        ),
        migrations.RemoveField(
            model_name='commonsdivisioncomment',
            name='division',
        ),
        migrations.RemoveField(
            model_name='commonsdivisionlike',
            name='baselike_ptr',
        ),
        migrations.RemoveField(
            model_name='commonsdivisionlike',
            name='division',
        ),
        migrations.RemoveField(
            model_name='lordsdivisioncomment',
            name='basecomment_ptr',
        ),
        migrations.RemoveField(
            model_name='lordsdivisioncomment',
            name='division',
        ),
        migrations.RemoveField(
            model_name='lordsdivisionlike',
            name='baselike_ptr',
        ),
        migrations.RemoveField(
            model_name='lordsdivisionlike',
            name='division',
        ),
        migrations.RemoveField(
            model_name='personcomment',
            name='basecomment_ptr',
        ),
        migrations.RemoveField(
            model_name='personcomment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personlike',
            name='baselike_ptr',
        ),
        migrations.RemoveField(
            model_name='personlike',
            name='person',
        ),
        migrations.DeleteModel(
            name='BaseComment',
        ),
        migrations.DeleteModel(
            name='BaseLike',
        ),
        migrations.DeleteModel(
            name='BillComment',
        ),
        migrations.DeleteModel(
            name='BillLike',
        ),
        migrations.DeleteModel(
            name='CommonsDivisionComment',
        ),
        migrations.DeleteModel(
            name='CommonsDivisionLike',
        ),
        migrations.DeleteModel(
            name='LordsDivisionComment',
        ),
        migrations.DeleteModel(
            name='LordsDivisionLike',
        ),
        migrations.DeleteModel(
            name='PersonComment',
        ),
        migrations.DeleteModel(
            name='PersonLike',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.VoteType'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('target_type', 'target_id', 'user'), name='unique_user_vote_per_target'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('target_type', 'target_id', 'text', 'user'), name='unique_comment_per_user_per_object'),
        ),
    ]
