# Generated by Django 3.0.7 on 2020-08-20 18:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import social.models.token


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200604_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='pending_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='pending_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.UserToken'),
        ),
        migrations.AlterField(
            model_name='signinserviceprovider',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='username',
            field=models.CharField(default=social.models.token._create_default_username, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Must start and end with alphanumerics. Otherwise also allow dash, underscore, dot. Minimum 4 characters.', regex='^[0-9a-zA-Z][0-9a-zA-Z-_.]{2,}[0-9a-zA-Z]$')]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.UserToken'),
        ),
        migrations.AlterField(
            model_name='votetype',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='UsernameChanged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('new_name', models.CharField(max_length=16)),
                ('previous_name', models.CharField(max_length=16)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.UserToken')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
