# Generated by Django 3.2 on 2021-09-02 17:33

from django.db import migrations, models
import util.time


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20200820_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='signinserviceprovider',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='usernamechanged',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='votetype',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
    ]
