# Generated by Django 5.1.2 on 2024-11-08 14:41

import django.db.models.deletion
import util.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0008_alter_vote_vote_type_delete_votetype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertoken",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="usertoken",
            name="provider_account_id",
        ),
        migrations.CreateModel(
            name="OAuthSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(default=util.time.get_now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=50)),
                ("user_id", models.CharField(max_length=50)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "user_id"),
                        name="unique_provider_user_id_per_provider",
                    )
                ],
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name="usertoken",
            name="oauth_session",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="social.oauthsession",
            ),
        ),
        migrations.DeleteModel(
            name="SignInServiceProvider",
        ),
    ]
