# Generated by Django 5.1.2 on 2024-11-08 15:15

import django.db.models.deletion
from django.db import migrations, models


def set_default_oauth_session(apps, schema_editor):
    OAuthSession = apps.get_model("social", "OAuthSession")
    UserToken = apps.get_model("social", "UserToken")

    for token in UserToken.objects.filter(oauth_session__isnull=True):
        token.oauth_session = OAuthSession.objects.create_default(token.username)
        token.save()


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0009_remove_usertoken_provider_and_more"),
    ]

    operations = [
        migrations.RunPython(
            set_default_oauth_session, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="oauth_session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="social.oauthsession"
            ),
        ),
        migrations.RenameModel(
            old_name="OAuthSession",
            new_name="OAuthToken",
        ),
    ]
