# Generated by Django 5.1.3 on 2024-11-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0010_alter_usertoken_oauth_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="oauthtoken",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="oauthtoken",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="usernamechanged",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="usernamechanged",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="usertoken",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="usertoken",
            old_name="modified_on",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="created_on",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="modified_on",
            new_name="modified_at",
        ),
    ]
