# Generated by Django 3.0.2 on 2020-01-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_tasknotification_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasknotification',
            old_name='timestamp',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.TaskNotification'),
        ),
    ]
