# Generated by Django 3.0.7 on 2021-04-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20210419_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknotification',
            name='level',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
