# Generated by Django 3.2.4 on 2021-11-24 15:31

from django.db import migrations


class Migration(migrations.Migration):
    replaces = [
        ("parliamentdotuk", "0001_initial"),
        ("parliamentdotuk", "0002_auto_20200820_1823"),
        ("parliamentdotuk", "0003_auto_20210521_1119"),
        ("parliamentdotuk", "0004_auto_20210902_1733"),
        ("parliamentdotuk", "0005_auto_20211101_1723"),
    ]

    initial = True

    dependencies = []

    operations = []
