# Generated by Django 3.0.2 on 2020-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillUpdateError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('parliamentdotuk', models.PositiveIntegerField()),
                ('error_message', models.CharField(max_length=1024)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'BillUpdateError',
                'verbose_name_plural': 'BillUpdateErrors',
            },
        ),
        migrations.CreateModel(
            name='CommonsDivisionUpdateError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('parliamentdotuk', models.PositiveIntegerField()),
                ('error_message', models.CharField(max_length=1024)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'CommonsDivisionUpdateError',
                'verbose_name_plural': 'CommonsDivisionUpdateErrors',
            },
        ),
        migrations.CreateModel(
            name='ElectionResultUpdateError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('parliamentdotuk', models.PositiveIntegerField()),
                ('error_message', models.CharField(max_length=1024)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ElectionResult Update Error',
                'verbose_name_plural': 'ElectionResult Update Errors',
            },
        ),
        migrations.CreateModel(
            name='LordsDivisionUpdateError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('parliamentdotuk', models.PositiveIntegerField()),
                ('error_message', models.CharField(max_length=1024)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'LordsDivisionUpdateError',
                'verbose_name_plural': 'LordsDivisionUpdateErrors',
            },
        ),
    ]
