# Generated by Django 3.2 on 2021-05-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliamentdotuk', '0002_auto_20200820_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='billupdateerror',
            name='trace',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='commonsdivisionupdateerror',
            name='trace',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='electionresultupdateerror',
            name='trace',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lordsdivisionupdateerror',
            name='trace',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='billupdateerror',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='commonsdivisionupdateerror',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='electionresultupdateerror',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lordsdivisionupdateerror',
            name='error_message',
            field=models.TextField(default=''),
        ),
    ]
