# Generated by Django 3.2 on 2021-09-02 17:33

from django.db import migrations, models
import util.time


class Migration(migrations.Migration):

    dependencies = [
        ('parliamentdotuk', '0003_auto_20210521_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billupdateerror',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='commonsdivisionupdateerror',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='electionresultupdateerror',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
        migrations.AlterField(
            model_name='lordsdivisionupdateerror',
            name='created_on',
            field=models.DateTimeField(default=util.time.get_now),
        ),
    ]
