# Generated by Django 3.2.4 on 2021-11-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliamentdotuk', '0004_auto_20210902_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillUpdateError',
        ),
        migrations.DeleteModel(
            name='CommonsDivisionUpdateError',
        ),
        migrations.DeleteModel(
            name='ElectionResultUpdateError',
        ),
        migrations.DeleteModel(
            name='LordsDivisionUpdateError',
        ),
    ]
